### ISSUE TITLE
Include Ex Commands for all the actions

### ISSUE THREAD

**Issue by thalesmello** [jalvesaq/Nvim-R#111]
Sometimes, remembering the name of a command is easier than remembering a shortcut for less frequently used action.

However, I've noticed only a handful of actions have Ex Commands.

Is there any particular reason those aren't configured?

**Comment by jalvesaq** [comment]
The only action that has both a shortcut and a command is `:Rhelp` because the user may want to call it with a function that is not in the script, and because with no arguments it call `help.start()`. All other actions have either a command or a shortcut.

Shortcuts are quicker to type and I don't like the idea of creating command that nobody will use. So, for the most frequently used actions, like sending line and sending selection, I think we should not create commands.

One useful command could be `:RAction` which would get the word under the cursor and send to R as the first argument of the chosen function. Other arguments for `:RAction` could be sent as further arguments for the function. For instance, if the cursor is over the word `obj`:

  - `:RAction print` would send to R `print(obj)`.
  - `:RAction print digits=2` would send `print(obj, digits=2)`.

However, if the user wants to send complex commands to R, it will be better to switch to R Console and to type the commands directly there.

Instead of creating commands for everything, I could create the R menu even when no gui is running. Then, users could access the menu with:
```
:emenu R.<C-D>
```

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).
