### ISSUE TITLE
Hide the `base::source` echo

### ISSUE THREAD

**Issue by scottstanfield** [jalvesaq/Nvim-R#124]
This plug in is working great, thank you. I almost have the RStudio ctrl-enter perfectly mapped to neovim. 

When I do blocks of code, then send with `\ss`, I get a `base::source` message.

Basically, I don't need to see this...How do I disable the `base::source` message or hide?

```
> base::source("/var/folders/k4/lh5y2dnd329_6_hwqj34y0jw0000gn/
T/Nvim-R-scott/Rsource-80190", print.eval=TRUE)
```

**Comment by jalvesaq** [comment]
It's not a message. It is code sent to R console. I could send the code through nvimcom but the rationale behind the current behavior is the following:

  - If R will execute code whose output will be seen in R Console, then the code is sent to R Console.
  - If R will execute code that will generate output in (Neo)Vim (show documentation, format code, make a list for autocompletion, make code for syntax highlight, etc), then this code is sent through nvimcom and you do not see it.

Instead of sending multiple lines, we have found it more reliable in the past to save the lines in a temporary file and source it because GNU screen used to choke with more than 4kb of code. Now, we use Tmux and Neovim buffer, and I could test whether they support large amounts of code. But, why would an user want to see a bunch of lines in the R Console if they are already in his or her script? This was another reason for using `source()`.

What exactly you want? Do you not want to see anything (`base::source()` or whatever) or do you want to see all the lines that are being source?

**Comment by scottstanfield** [comment]
This is a great response; thank you. I think I understand the limitations now. 

I was able to work around my problem earlier due to a great comment in your source: the part requiring an <Esc> before :call to avoid multiple lines being sourced, rather than one at a time. 

So it's up to you if you wish to close this issue. The request remains: don't show the base::source message (to avoid cluttering the terminal window). But since that's how you get multiple lines to work, then I don't see a practical way to accommodate my request. 

Regardless: thank you for building this. I can't tell you how much time I save using neovim over RStudio!

---
Scott Stanfield
scottstanfield@gmail.com

**Comment by scottstanfield** [comment]
Adding this here in case someone stumbles across it. I was able to clean up the `base::source` "noise" by adding the following to my `.vimrc`

```
let R_source_args = 'print.eval=F'
```

Now when I source a block, the output window is quieter.

**Comment by jalvesaq** [comment]
Great! I am closing the issue because It would be problematic to send `base::source()` to nvimcom instead of sending it to R Console.
