### ISSUE TITLE
R environments managed by conda

### ISSUE THREAD

**Issue by daler** [jalvesaq/Nvim-R#133]
Hi - 
I'm using the [conda](http://conda.pydata.org/docs/) package manager to manage isolated R environments. Conda essentially manipulates the path such that the directory in which a particular version of R is installed is prepended to the PATH.

Nvim-R works great in the root conda environment. So installation doesn't seem to be an issue.

But when I create a new environment and activate it, like this:

```bash
conda create -n example --channel r r 
source activate example
pip install neovim
``` 

when starting R with `<LocalLeader>rf`, I get the error:

```
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE, :                         
  there is no package called ‘nvimcom’
2: package ‘nvimcom’ in options("defaultPackages") was not found
```

Any suggestions on what I could try? Thanks.

**Comment by jalvesaq** [comment]
I expected that nvimcom would be automatically installed in each environment when R is started with `<LocalLeader>rf`.

Note: The Rprofile should NOT have either `library(nvimcom)` or `require(nvimcom)`.

**Comment by daler** [comment]
That's what I was thinking, too. I don't have any `.Rprofile` files, so that doesn't seem to be the issue.

**Comment by jalvesaq** [comment]
It seems that Vim thinks that nvimcom is installed. If you do in Vim `:echo rplugin_compldir` you will know where Vim is looking for the file `nvimcom_info`. In my system, it is located at `~/.cache/Nvim-R/nvimcom_info`. This file is created by nvimcom and it has three lines. The second one is the path to where nvimcom is installed. Vim checks whether the directory still exists and it only rebuilds nvimcom if the directory no longer exists (because you manually `remove.packages("nvimcom")`) or if the version indicated at `nvimcom/DESCRIPTION` is the incorrect one.

**Comment by daler** [comment]
Aha! Deleting that file between environment switches fixes the issue. Thanks so much, would have taken me forever to find that.
