### ISSUE TITLE
Is RStudio integration possible with Nvimcom?

### ISSUE THREAD

**Issue by gwerbin** [jalvesaq/Nvim-R#142]
I love everything about the RStudio IDE, but I'd love it even more if I could write code in a Neovim window (either a terminal or one of the GUI wrappers like VimR) and send it to the R session running inside RStudio.

How tightly coupled in Nvimcom to running R specifically inside a Neovim terminal? Can it be adapted to interface with R instances _outside_ Neovim? If so, can it interface specifically with the R sesion inside RStudio? And how difficult would this adaptation be?

**Comment by jalvesaq** [comment]
The best solution would be if RStudio allowed its editor being replaced by another editor.
Neovim was designed to be easily embedded, and it already has a Qt interface: https://github.com/equalsraf/neovim-qt
It should no be too difficult for someone who knows C++ and Qt to integrate Neovim into RStudio.

Regarding your question, because RStudio has a free version, I think it would not be difficult to find what of its internal functions is responsible for pasting commands into its R Console. Then, Nvim-R would send the command to nvimcom which would paste it into RStudio. This is what I have done for the Rgui on Windows. But I guess such a function in RStudio is not accessible from an R package as it is in Rgui. So, probably you would have to maintain your own custom version of RStudio.

If RStudio had an R command to paste lines of code into its R Console, it would be really easy to do what you want because it would be necessary only minor changes in Nvim-R and nvimcom, instead of modifying RStudio code.

**Comment by FvD** [comment]
Would it not be possible using the RStudio API through the [rstudioapi package](https://cran.rstudio.com/web/packages/rstudioapi/rstudioapi.pdf)? There a `sendToConsole()` function that basically does what @gwerbin is looking for.

**Comment by jalvesaq** [comment]
I think so. I did not know about rstudioapi, but I may try it latter this week.

**Comment by jalvesaq** [comment]
@gwerbin Please, try the branch https://github.com/jalvesaq/Nvim-R/tree/rstudio

**Comment by nacnudus** [comment]
This would be an amazing feature.  It is failing on Linux due to calling `SetRHome()`.

**Comment by jalvesaq** [comment]
Thanks for testing it. I could not install RStudio on Ubuntu 16.10. Then, I tested the changes only on Windows. Please, let me know if it works on Linux now.

**Comment by jalvesaq** [comment]
See: https://github.com/jalvesaq/Nvim-R/commit/3be5a3f482e8bec276a48f71388be0f7f8734c13

**Comment by gwerbin** [comment]
This looks great! I'll try it this morning on macOS.

**Comment by gwerbin** [comment]
I just tried to configure this, but it doesn't seem to work. This is what's in my `init.vim`:

```vim
let R_assign = 3
let R_in_buffer = 0
let Rstudio_cmd = '/Applications/RStudio/Contents/MacOS/RStudio'
```

But it just opens a new terminal tab instead.

**Comment by jalvesaq** [comment]
I am sorry, but I don't have access to any Mac OS X to test. Anyway, what command would you type in a terminal emulator to open RStudio?

**Comment by gwerbin** [comment]
Typically it would be

```shell
open -a RStudio
```

but

```shell
/Applications/RStudio.app/Contents/MacOS/RStudio
```

does also work.

**Comment by jalvesaq** [comment]
And, does this work?
```
let RStudio_cmd = "open -a RStudio"
```

**Comment by gwerbin** [comment]
No, same effect.

Do you have a quick summary of how you implemented this? Since it works on Windows and Linux, maybe it's jus a quick fix on Mac that I can look into.

**Comment by gwerbin** [comment]
Alternatively (and perhaps preferably) would it be possible to "register" an existing R session instead of always opening a new one?

**Comment by nacnudus** [comment]
The command to open RStudio is fundamentally `jobstart("open  -a RStudio")`, or whatever you assign to `RStudio_cmd`.

**Comment by jalvesaq** [comment]
It's not possible to register an existing R session because nvimcom needs some environment variables to know where to save files, what "password" to use to send messages to Nvim-R, etc.
But I could consider the creation of the Vim command `:RSaveConnectionInfo filename` and the nvimcom function `read.connection.info("filename")`.

**Comment by jalvesaq** [comment]
@gwerbin, as @nacnudus told, if you are using Neovim, you could try in Normal mode:
```
:call jobstart("open -a RStudio")
```
And, if you are using Vim:
```
:call job_start("open -a RStudio")
```

**Comment by gwerbin** [comment]
@jalvesaq if I wanted to put something like that together, where might I start looking in the code?

**Comment by jalvesaq** [comment]
Functions `StartR()` and `GetNvimcomInfo()` at `R/common_global.vim`.

**Comment by jalvesaq** [comment]
Looking on how `R.app` is started by `R/osx.vim`, I guess the command to open RStudio could be
```vim
let g:Rstudio_cmd = 'open /Applications/RStudio'

```

**Comment by tinyheero** [comment]
FYI, I got this to work on my Mac by:

1. Installing rstudio using conda:

    ```
    conda install -c r rstudio
    ```

2. Adding to my `~/.config/nvim`:

    ```
    let R_in_buffer = 0
    let RStudio_cmd = "/Users/f.chan/miniconda3/bin/rstudio"
    ```

This worked fine for me. Using Neovim (v0.2.0) and the Nvim-R (v0.9.10)
