### ISSUE TITLE
Making vim send R lines to a terminator pane

### ISSUE THREAD

**Issue by PiggyGenius** [jalvesaq/Nvim-R#161]
Hello,

I am not sure it is a real issue or a "missing feature" but I can't use Nvim-R the way I would like to so I guess the best way to know is to raise the issue.

I am using terminator (allows me to have multiple terminal instances in one window) and I would like to have one of the terminals open (I have four) to be the R instance that Nvim will send the R code to.

I managed to make it work with tmux, so what works for now is that when I launch R from vim, it splits my terminal into two tmux panes and one of those is R. I would really like to be able to tell to Nvim which terminal instance it should use or maybe which already opened R instance it should use. That is because I don't want to use tmux and since I already have the terminal opened, it seems it is only a matter of sending the data to the correct terminal ?

Please let me know if it is possible with Nvim and if it is not would you mind telling me a bit more about how you can select vim lines from a buffer and send those to R instance maybe without having to go through tmux ?

Thanks a lot.

**Comment by jalvesaq** [comment]
I am sorry, but what you want is not supported. In the past, I have switched from `funnel.pl` to GNU `screen` and from the later to Tmux. Now, in addition to running R in an external terminal emulator, it is possible to split a Tmux window or run R in a Neovim built-in terminal emulator. It would be too time consuming supporting another way of running R. The only way of not using Tmux to send code to R is using Neovim. If someone writes the code to use Terminator instead of Tmux, I will mention the code at the section `R_source` of Nvim-R documentation. Please, see:
```
:h R_source
```
