### ISSUE TITLE
Autocompletion

### ISSUE THREAD

**Issue by ErickChacon** [jalvesaq/Nvim-R#175]
I was wondering if there any setting for autocompletion, so we no need to type `<c-x><c-o>`. If not, maybe an integration with another plugin could be allow. For example, [Ultisnips](https://github.com/SirVer/ultisnips) is automatically integrated with [deoplete.nvim](https://github.com/Shougo/deoplete.nvim/) such as `Ultisnips` snippets appears on the pop-menu provided by `deoplete.nvim`. I think an integration like that would be nice. To not slow it down, maybe at least the completion based on some predefined packages, `let R_start_libs = "base,stats,graphics,grDevices,utils,methods"`, could be shown on `deoplete.nvim` pop-up.

**Comment by jalvesaq** [comment]
The documentation has a tip on how to use Ctrl+Space for omnicompletion. Please, do
```
:h Nvim-R-vimrc-setup
```
People might never agree on what is the best plugin for completion. So, if I work for integrating Nvim-R with one specific plugin, other people will request integration with other plugins.

And I don't think that any plugin will be smart enough to know when I want omnicompletion or word completion or dictionary completion or thesaurus completion, etc... I even can't distinguish unambiguously when the user wants omnicompletion or function arguments completion because in R we can pass a function with arguments as argument to another function. So, I prefer different commands for different kinds of completion.

So, I am sorry, but you have to try the integration in your vimrc. If you or someone else writes a complement for Nvim-R integrating it with another plugin, I will add a reference to the script to Nvim-R documentation. Please, see:
```
:h R_source
```

**Comment by ErickChacon** [comment]
Thanks for the answer. I have already mapped the omnicompletion and I think that works fine. With respect to the integration, I think I will try, but not in a near future. Thanks for your awesome plugin.

**Comment by statquant** [comment]
@ErickChacon would you kindly share you mapping setup ?

**Comment by ErickChacon** [comment]
> @ErickChacon would you kindly share you mapping setup?

It is a long time I opened this issue. Now, I use `deoplete.nvim` and  `LanguageClient-neovim` (it uses Language server protocol) for completion and additional characteristics. You can use it for several languages. Here is the plugins installation (you can remove the commits, I just do it to not find unexpected new bugs):
```
Plug 'autozimu/LanguageClient-neovim'  , {'commit': '41c948e',
      \ 'branch': 'next', 'do': 'bash install.sh'}
Plug 'Shougo/deoplete.nvim'            , {'commit': '3e3b762',
      \ 'do': ':UpdateRemotePlugins' }
```
taken from https://github.com/ErickChacon/stat-toolbox/blob/84cb3da41835998656a8611f99a33b0d690f4c63/3.6.0/nvim/plugins.vim#L16-L19
And here is my configuration for `languageclient-neovim`:
```
set hidden
let g:LanguageClient_serverCommands = {
    \ 'r': ['R', '--quiet', '--slave', '-e', 'languageserver::run()'],
    \ 'rmd': ['R', '--quiet', '--slave', '-e', 'languageserver::run()'],
    \ }
let g:LanguageClient_autoStart = 1
```
taken from https://github.com/ErickChacon/stat-toolbox/blob/84cb3da41835998656a8611f99a33b0d690f4c63/3.6.0/nvim/init.vim#L458-L470
Feel free to explore my `init.vim` file if something is missing.

**Comment by statquant** [comment]
@ErickChacon oh it seems to be working that’s great. But do you get arguments of functions within f( ? This does not work for me
