### ISSUE TITLE
Vimshell

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#178]
What would it take to run Nvim-R with an R session running on windows in VimShell https://github.com/Shougo/vimshell.vim. I am using vim btw

**Comment by jalvesaq** [comment]
You would have to write the code integrating the two plugins, and I would mention it at Nvim-R documentation. See:
```vim
:h R_source
```
I am sorry, but I'm not going to do this because I run R in a neovim terminal buffer on Linux, and I only reboot my computer into Windows before releasing a new version of Nvim-R to check whether it still works there.

**Comment by blayz3r** [comment]
Ok cool thanks, I will give you a heads up if I write a script
