### ISSUE TITLE
Cross-machine communication in local network

### ISSUE THREAD

**Issue by klmr** [jalvesaq/Nvim-R#180]
Nvim-R’s help file notes that

> both R and Vim must be in the same machine because the TCP communication between them is limited to localhost

Are there any plans to implement this in the future? I’m using Nvim-R extensively on a cluster, and, due to strict resource limitations, interactive R must effectively be run through a job scheduler (LSF). Conversely, interactive Vim and tmux must be run on a head node.

At the moment I have `R_cmd` set to a custom script which contains something like the following to dispatch the R call:

```bash
bsub -Is "$(which R) $@"
```

Where `bsub` is the name of the command to submit jobs to the scheduler. This “works” insofar as that Vim can now send commands to R. But the inverse communication doesn’t work: no specific syntax highlighting of loaded function names, no auto-completion, no help, and presumably no object browser (but I never use that anyway). The help in particular is annoying since this disables *all* help display, even the one inside R.

Support for this would be great. Of course I can see that it’s not trivial to implement — and unfortunately I have no help to offer, knowing next to nothing about TCP communication.

**Comment by jalvesaq** [comment]
I don't have your setup, so it is nearly impossible to me to support it, but if it is just a matter of setting the IP addresses (instead of using localhost), then we could use either environment variables or Vim variables pointing to the correct addresses.

If you know the IP addresses of both server and client, you could try replacing the string `"127.0.0.1"` with appropriate values in `R/nvimcom/src/nvimcom.c` and `R/nvimcom/src/apps/nclientserver.c`. Then, you should delete `~/.cache/Nvim-R/nvimcom_info` to force nvimcom being "updated".

If possible, you should also set the values of both `R_tmpdir` and `R_compldir` to directories shared over the network, so Vim would be able to read files written by R. In fact, in Vim cannot read files written by R, the TCP communication will be useless.

**Comment by klmr** [comment]
For cluster load scheduling, the IP addresses/hostnames are dynamic. So for this to work, both R and Vim would have to determine their respective IP addresses and somehow communicate them to each other.

The file system isn’t a problem on the other hand: the relevant location is mounted on the whole cluster.

**Comment by jalvesaq** [comment]
My IP address is on the wlan0 interface; others will be on eth0. So, I think the best option is using two environment variables `R_IP_ADDRESS` and `VIM_IP_ADDRESS`. If these variables existed, they would be used for `getaddrinfo()`, and it would be up to the user to set these variables with the correct values. I may create a new branch to test this...

**Comment by klmr** [comment]
Unfortunately the user will only know the IP address of Vim beforehand. The IP address of the machine where R runs can only be discovered *after* R has launched. If the user is allowed to assign the environment variable after the R instance has launched, then this approach may work. :-)

**Comment by jalvesaq** [comment]
Yes, this code in the .Rprofile works for me:
```r
myip <- system("ifconfig", intern = TRUE)
myip <- myip[grep("wlan0", myip) + 1]
myip <- sub(" *inet ", "", myip)
Sys.setenv("R_IP_ADDRESS" = sub(" .*", "", myip))
rm(myip)
```
But the Object Browser is not being updated... I will try again later.

**Comment by jalvesaq** [comment]
Please, delete your `~/.cache/Nvim-R/nvimcom_info` and try this branch: https://github.com/jalvesaq/Nvim-R/tree/ip_address

I put in my vimrc:

```vim
let $NVIM_IP_ADDRESS = split(system("ifconfig | grep -C 1 wlan0 | tail -n 1 | sed -e 's/^ *inet \\(.*\\) netmask.*/\\1/'"), "\n")[0]
```

and in my `~/.Rprofile`:

```r
myip <- system("ifconfig", intern = TRUE)
myip <- myip[grep("wlan0", myip) + 1]
myip <- sub(" *inet ", "", myip)
Sys.setenv("R_IP_ADDRESS" = sub(" .*", "", myip))
rm(myip)
```

And it works, but with both Neovim and R in the same machine.

**Comment by jalvesaq** [comment]
Using the `ip_address` branch, I was able to connect through ssh to my own laptop with the following procedure:

   1. My `$PATH` includes `~/bin` and I have a symbolic link to R in this directory. So, I created the file `~/bin/sshR` (local machine) with the following contents:

```sh
#!/bin/sh
ssh -p 222 -t login@hotname.local "PATH=~/bin:$PATH NVIMR_TMPDIR=$NVIMR_TMPDIR NVIMR_COMPLDIR=$NVIMR_COMPLDIR NVIMR_ID=$NVIMR_ID NVIMR_SECRET=$NVIMR_SECRET R_DEFAULT_PACKAGES=$R_DEFAULT_PACKAGES NVIM_IP_ADDRESS=$NVIM_IP_ADDRESS R"
```

   2. I am connected to the internet through a wireless router (`wlan0` interface). So, I put in my `~/.config/nvim/init.vim` (local machine):

```vim
let $NVIM_IP_ADDRESS = split(system("ifconfig | grep -C 1 wlan0 | tail -n 1 | sed -e 's/^ *inet \\(.*\\) netmask.*/\\1/'"), "\n")[0]
let R_app = "sshR"
```

   3. Finally, I put in my `~/.Rprofile` (remote machine):

```r
myip <- system("ifconfig", intern = TRUE)
myip <- myip[grep("wlan0", myip) + 1]
myip <- sub(" *inet ", "", myip)
Sys.setenv("R_IP_ADDRESS" = sub(" .*", "", myip))
rm(myip)
```

Notes for someone trying to run Vim (or Neovim) in one machine and R in a remote machine, sending commands to R through ssh:

   1. You will get omnicompletion, arguments completion, automatic update of the syntax highlight, R help in Vim, etc, only if both `$NVIMR_TMPDIR` and `$NVIMR_COMPLDIR` are directories shared through the network. Otherwise, the `_IP_ADDRESS` configurations will be useless.

   2. If necessary, you may set different names for `R_tmpdir` and `R_compldir` in your `vimrc` (local machine) and for `$NVIMR_TMPDIR` and `$NVIMR_COMPLDIR` in the `sshR` script (local machine, but referring to the remote machine). What really maters is that `R_tmpdir` and `$NVIMR_TMPDIR`, and `R_compldir` and `$NVIMR_COMPLDIR` are the same directories.

   3. If your R in the remote machine needs additional environment variables, you have to add them to `sshR`.

   4. For someone who can login in the remote machine through ssh, it is much simpler to run both Vim (or Neovim) and R in the remote machine. You should do it unless you can't install either Neovim or Vim and Tmux in the remote machine.

**Comment by klmr** [comment]
I’m currently trying this and I am unfortunately hitting a road block when starting R from Vim: nothing happens. Vim hangs shortly and then acts as if nothing had happened. No diagnostic output is provided. Could you tell me if there are log files anywhere?

Concerning the instructions you provided in the Nvim-R help file:

* I’d recommend adding a check for `interactive()` around the `.Rprofile` configuration, e.g.:

```r
if (interactive()) {
    local({
        myip <- system("ifconfig", intern = TRUE)
        myip <- myip[grep("site", myip) + 1]
        myip <- sub(" *inet ", "", myip)
        Sys.setenv("R_IP_ADDRESS" = sub(" .*", "", myip))
    })
}
```

* The directories should probably be under `~/.R` not `~/R`, right? What’s the `libraries` directory for?

* If the directories are mounted under the same mount point locally and remotely, do I need to specify the `R_tmp_remotedir` in Vim?

**Comment by jalvesaq** [comment]
- I will add the `interactive()` and `local()` to the example.

  - The directories might have any name. The `libraries` might be the default directory used by R to install user packages.

   - You do not have to specify `R_remote_tmpdir` if you set `R_tmpdir` as a subdirectory of a directory that you will mount before starting Vim. Note that if your shared directory in inside your home directory in the remote machine your login name must be the same in the two machines.

  - You do not have to specify `R_nvimcom_home` if the Nvim-R plugin is installed in the remote machine and its path is exactly the same as that of the local machine.

**Comment by klmr** [comment]
I’ve managed to fix the hang I experienced previously: the `R_IP_ADDRESS` was calculated wrongly, at least on my system. The fixed code looks as follows:

```r
if (interactive()) {
    local({
        ifconfig <- system('ifconfig', intern = TRUE)
        inet <- ifconfig[grep('^site', ifconfig) + 1]
        ip_address <- regmatches(inet, regexpr('addr:[0-9.]+', inet))
        Sys.setenv(R_IP_ADDRESS = sub('addr:', '', ip_address))
    })
}
```

Likewise, on the Vim side the code needs to look as follows for me:

```vim
let $NVIM_IP_ADDRESS = system("ifconfig | grep -A 1 site | tail -n 1 | grep -o '[[:digit:].]*' | head -n 1")
```

With these changes in place, **it works for me**. :+1:

For reference, the relevant line of my `ifconfig` output looks as follows:

```
            inet addr:172.17.122.10  Bcast:172.17.122.255  Mask:255.255.255.0
```

Unfortunately the code I wrote above might not be general enough to work on other systems, and in fact it *won’t* always work because the `inet` line doesn’t immediately need to follow the header — it can be anywhere after it, so looking at the line after `site` or `wlan0` or `en0` or whatever won’t work.

Furthermore, the above somehow unfortunately stops #173 from working properly: even subsequently setting `R_rconsole_width` manually has no effect. :-/

**Comment by klmr** [comment]
In fact, on Linux a *much* easier option is to use `hostname -I | head -1`. However, this flag doesn’t exist e.g. on macOS.

**Comment by jalvesaq** [comment]
I fixed some mistakes in the documentation and now I could successfully run (in the same machine) Vim from one account and R from another, mounting the directories with `mountR` script.

**Comment by jalvesaq** [comment]
@klmr I have just tested with two Linux machines connected to the same wireless network. The local machine does not have R installed, and everything is working with `ssh -t` in the `R_app` script. I believe it will also work if you replace `ssh -t` with `bsub -Is` in your `R_app` script.

**Comment by jalvesaq** [comment]
I have just incorporated the `ip_address` branch changes into `master` and deleted the branch.

**Comment by klmr** [comment]
Thanks, phenomenal effort. I’ve been using this branch for a few days now. I’ll keep filing reports with issues as I find them (and, with a bit of luck, with fixes ;-)).
