### ISSUE TITLE
Sending a full paragraph to R console

### ISSUE THREAD

**Issue by mattcbowers** [jalvesaq/Nvim-R#185]
Is it possible to send an entire paragraph of R code to the console  from any position in the paragraph? I noticed that <LocalLeader>pp and its friends pe and pa only send the lines from the cursor position down to the next blank line. I'd like to send an entire paragraph from any position in that paragraph.

**Comment by jalvesaq** [comment]
Currently, it is not possible, but it would be easy to implement. We have two options:

   - Create an option like `R_paragraph_begin` to change the behavior of `<LocalLeader>pp`.

   - Create another map for this, but I can't think of anything better than `<LocalLeader>pp`.

I prefer the first option because any letter other than `p` for the map would not be intuitive. Moreover, I prefer the suggested behavior as default. Currently, users are supposed to use marked blocks for this, but sending paragraphs is more convenient because there is no need of marking the text.
