### ISSUE TITLE
R quits immediately after starting on Windows with neovim-qt

### ISSUE THREAD

**Issue by wngrtn** [jalvesaq/Nvim-R#195]
I just started using `neovim-qt` on Windows. Unfortunately, I cannot get Nvim-R to work. When I run `\rf`, a buffer with an R session opens in a split. It is populated with R's welcome message, then shows the line `Rterm.exe --nosave && exit` and neovim raises the error `"R" exited with status 1`. Where do I start diagnosing this?

**Comment by jalvesaq** [comment]
I'm waiting for https://github.com/neovim/neovim/pull/6383

**Comment by jalvesaq** [comment]
@wngrtn If you wanted to test the pull request 6383, you could download the Neovim executable from the AppVeyor build at the end of the pull request conversation page. You would have to click on:

   - Details
   - MINGW_64
   - ARTIFACTS
   - build\Neovim.zip

**Comment by wngrtn** [comment]
Thank you! I tried the AppVeyor build and it does indeed allow me to open and close an R session without failing.

When I send commands to R it sometimes works, but sometimes R crashes. Here is the error message that I sometimes get in response to 1) Start Nvim-QT 2) `:e ~\test.R` 3) Use `\rf` to start R 4) Use `\ll` to send the line `a <- 15`:

```
> a <- 15
Warning: stack imbalance in 'lazyLoadDBfetch', 16 then -11

[Process exited -1073741819]
```

Do you want me to file that as a new issue?

**Comment by jalvesaq** [comment]
I think that the imbalance happens when a command is sent to R before it is really ready. If R is being started for the first time, it will not be cached in Windows memory and will take longer to start. That is, to replicate the bug, you should send a line to R as soon as Nvim-R allows you to do so.

I have just increased from 300 to 1200 ms the time that Nvim-R waits to consider that R is ready after receiving the message that nvimcom was loaded. Perhaps this is enough to avoid the stack imbalance. If not, it will be good to file a new issue.

**Comment by jalvesaq** [comment]
@wngrtn Do you still see the bug?
