### ISSUE TITLE
syntax colouration

### ISSUE THREAD

**Issue by FanchCollin** [jalvesaq/Nvim-R#196]
I have used the plugin for a long time now (wonderful plugin by the way, many thanks). 

However I have constantly faced a problem with the code colouration: for my long Rnw scripts mixing R and latex codes the colouration doesn't follow. It doesn't recognised what is from R and what is LaTeX so there is no more colouration. 

The plugin is so good that I have resigned using the syntax colouration but it would be a plus if it was improved. 

![rvimplugin_nocolouration](https://cloud.githubusercontent.com/assets/16820012/26283176/cd63fc10-3e22-11e7-90f3-1c08c75a1ef2.png)

**Comment by jalvesaq** [comment]
It looks like you are using custom folding, defined by `}}}`, but since Rnoweb is a mix of LaTeX and R, the syntax highlighting algorithm needs some points of reference to know for sure that the code is either LaTeX or R. Vim does not calculates the syntax for the entire document, only for the visible part of it and a few lines above. When it finds the string "^<<", it knows that R code begins, but, in your screenshot, the chunk header is folded. So, you could trying not using custom folding.

I see this syntax issue more frequently in Rmd than in Rnoweb, and I couldn't find a way of fixing it, so I created a function to restart the syntax highlight in my vimrc (`~/.config/nvim/init.vim`), and I press `<F7>` to call it:

```
function RestartSyntax()
    let thisft = &filetype
    set ft=none
    exe "set ft=" . thisft 
endfunction
nmap <F7> :call RestartSyntax()<CR>
```

@jranke is the maintainer os `syntax/rnoweb.vim` and he might have better advices.

**Comment by FanchCollin** [comment]
Thanks, that is a perfect alternative !
