### ISSUE TITLE
Failed to parse arguments: Cannot open display

### ISSUE THREAD

**Issue by timedreamer** [jalvesaq/Nvim-R#198]
Hi, I installed Nvim-R by Vundle , but when I press `\rf` I got the following error message. Any ideas why? It seems like a display issue, does Nvim-R need X11 display? R version is 3.4.0, Vim version  8.0.

 Thanks!

```
Messages maintainer: Bram Moolenaar <Bram@vim.org>
"test.R" 0L, 0C
[Terminal emulator] Failed to parse arguments: Cannot open display:
"Job" exited with status 1
R did not load nvimcom yet
```

**Comment by jalvesaq** [comment]
Neovim does not require an external terminal emulator because it has its built-in terminal, but Vim does, and the terminal emulator might need X11, depending on your system. Your options are:

   1. Use Neovim (recommended).
   2. Put in your vimrc `let R_tmux_split=1`, start `tmux`, and start Vim inside `tmux`.

Please, see `:h Nvim-R-Tmux`.

**Comment by timedreamer** [comment]
awesome. Problem fixed! Thank you!
