### ISSUE TITLE
Can not scroll with vim/tmux

### ISSUE THREAD

**Issue by mschubert** [jalvesaq/Nvim-R#200]
I am unable to scroll in the `tmux` pane where `R` starts. Entering copy mode works just fine, but then the indicator always reports `[0/0]` lines to scroll. In `tmux` alone this works without problems.

* vim 8.0.106
* tmux 2.3

```
# .vimrc
let g:R_term = 'tmux'
let g:R_term_cmd = 'tmux split-window -c "#{pane_current_path}"'
```

Any idea on why this could be?

![screenshot from 2017-06-08 23-13-32](https://user-images.githubusercontent.com/442360/26953129-81fd7b20-4ca0-11e7-99b9-56b8cc90206f.png)

**Comment by jalvesaq** [comment]
Please, read the section `Nvim-R-Tmux` of Nvim-R documentation because the options `R_term` and `R_term_cmd` are for setting an external terminal emulator.

**Comment by mschubert** [comment]
It was `let g:R_tmux_split = 1` that was missing.

I somehow missed that, thank you!

**Comment by edwmurph** [comment]
@jalvesaq I'm seeing this problem and tried the solution discovered in this thread but it didn't work for me. I'm using iterm2 and osx 10.13.3. I tried the instructions specified in the "Key bindings and mouse support~" section of the Nvim-R documentation. Specifically, entering scroll mode doesn't even work for me. With the cursor in the R pane, I tried the following commands to enter scroll mode but they don't work for me: `<C-a>[` ,`<C-a><C-a>[` and `<C-b>[`. I would prefer to be able to scroll with my mouse but if I could at least be able to scroll by entering scroll mode that would at least be usable.

```
$ tmux -V
tmux 2.6

$ vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar  2 2018 02:50:34)
macOS version
Included patches: 1-1553

**Comment by jalvesaq** [comment]
I'm sorry, but I decided to stop the support for running R in a Tmux split pane because I no longer use this feature. As I have just told at https://github.com/jalvesaq/Nvim-R/commit/f3f33f1331c483b91cd48071f73a12fdb7b18955 if the feature in its current state becomes buggy I will rather completely remove it than fix it. If someone wants to keep the support for this feature, the better option would be to copy the corresponding code to another repository, which I would refer to in the section "Source additional scripts" of Nvim-R documentation.
