### ISSUE TITLE
Syntax Folding - `zc` closes all folds initially

### ISSUE THREAD

**Issue by tinyheero** [jalvesaq/Nvim-R#211]
I am a bit confused as to how folding is supposed to work with Nvim-R. Right now, I have the following settings in my `~/.config/nvim/init.vim`:

```
let r_syntax_folding = 1
set nofoldenable
```

So I have folding set, but when I open a file all folds should be open. This way, I can manually toggle when a fold should be closed. When I hover over a chunk of code that can be folded and enter `zc`, all folds get closed instead of just the chunk that I wanted to be folded.

Interesting, if I start opening all the folds and then use `zc` then each fold is closed properly. So in other words, it seems the first usage of `zc`seems to not follow the intended behaviour?

**Comment by jalvesaq** [comment]
The same happens with C code. So, this is not a [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime) bug.

Note that the first `zc` displays the error message `E490` and that Vim's documentation (`:h 'foldenable'`) says:

> This option is set by commands that create a new fold or close a fold.

So, what happens is:
  - There is no fold in the window because you started Vim with 'nofoldenable'.
  - When you try to close a fold, this is an error because there no fold yet, but the option 'foldenable' is set and, consequently, all folds are created.
