### ISSUE TITLE
Vim Terminal

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#218]
This may be a bit premature but do you envision Nvim-R using vim 's terminal feature  going forward.

**Comment by jalvesaq** [comment]
Yes, I will do it soon.

**Comment by jalvesaq** [comment]
I did
```
:terminal R
:call term_sendkeys(2, "ls()\n")
```
and it took 4 seconds to see the output of `ls()` in the terminal. So, I think the terminal is not ready to be used yet.

**Comment by blayz3r** [comment]
I agree, I think it's at least a couple weeks away.Thanks for the update

**Comment by blayz3r** [comment]
Issue should be fixed now https://github.com/vim/vim/issues/1966

**Comment by jalvesaq** [comment]
Please, try it now.

**Comment by blayz3r** [comment]
Did some quick checks and it works, I will it you know if I have any issues .

**Comment by blayz3r** [comment]
After updating the plugin today, my terminal is now vertical and I have had a few crashes.

**Comment by jalvesaq** [comment]
You can control whether the terminal will be horizontal or vertical with the options `R_rconsole_height`, `R_rconsole_width`, and `R_min_editor_width`. These options were already used with Neovim. The R option `width` is also being automatically updated. Now, only the syntax highlighting of R's output is still missing in Vim.

Can you describe a reliable way of replicating the crash?
Do the crashes get fixed if you put this in your vimrc?
```vim
let R_setwidth = 0
```

**Comment by blayz3r** [comment]
When I open R and try to send a line using <leader>l
![rcrash](https://user-images.githubusercontent.com/12205650/29344921-3af9f94e-8209-11e7-94b8-17ce8f405d59.png)
I will try to set the option in my vimrc

**Comment by jalvesaq** [comment]
I think that the option will fix the issue...

This is a limitation of R on Windows. I cannot queue commands, and they get executed immediately and are internally mixed with commands sent to R Console. While writing C code in R, if I call `PROTECT()` n times, I have to call `UNPROTECT()` exactly n times too, and code running in other threads cannot be executed simultaneously because the `UNPROTECT()` of one thread will unprotect the code of the other thread. Unless someone knows how to solve this issue, I will have to disable automatic update of the `width` option on Windows. Another possibility is to send the `options(width=X)` to R Console instead of executing the command internally into nvimcom.

**Comment by jalvesaq** [comment]
I tested it here and it is not crashing with vim_8.0.0946_x64 running R 64bit.

**Comment by blayz3r** [comment]
I set R_setwidth = 0 and the crashes stopped.
