### ISSUE TITLE
Could Nvim-R + Vim8.0 (in windows 10) run R in buffer?

### ISSUE THREAD

**Issue by research41** [jalvesaq/Nvim-R#222]
when I installed Nvim-R , everything works great.
However if I press \rf, starting R. the R console is separated from vim.
It should be in vim buffer as help-doc said, right?

**Comment by jalvesaq** [comment]
R will run in a Vim buffer if you install the development version of Nvim-R from github and if Vim >= 8.0.0946.

**Comment by research41** [comment]
I have installed development version of Nvim-R  by  "git clone  https://github.com/jalvesaq/Nvim-R.git"
and my gvim is already vim8.0.0946. 

However when I press \rf, It repoted an nvimcom install error, as following
<img width="889" alt="20170816181350" src="https://user-images.githubusercontent.com/27892267/29387596-bc06d4b2-82ae-11e7-9a94-1dc897aca991.png">

**Comment by jalvesaq** [comment]
It seems that there is something wrong with your Nvim-R installation...
Anyway, could you try Neovim? I tried the development version (pre-release) nvim-win64.zip from https://github.com/neovim/neovim/wiki/Installing-Neovim

I noted that I have to manually move the cursor to the end of R Console buffer after starting R, otherwise the output does not scroll when new lines are sent, but other than that it seems to work well:
<img width="494" alt="neovim_capture" src="https://user-images.githubusercontent.com/891655/29391520-3be2fdc2-82ce-11e7-8fdf-045600698f61.PNG">

**Comment by research41** [comment]
Hi jalvesaq,
     It still doesn't work on my computer( windows10+Neovim_development_Version+NVim-R_development_version). the problem is almost the same as the last one when I use vim8.0.0946.
so I think, it is not about vim or neovim. 
    Currently, I back to use Nvim-R from vim.org.  I works except running R console in vim buffer.
    Thanks again. I am waiting for next Nvim-R version

**Comment by research41** [comment]
Amazing! 
When I use  Nvim-R from vim.org+ Neovim_development_Version, it works perfectly.

**Comment by LouisAsh** [comment]
I have almost the exact same problem as the original one posted here, except that I am using gVim. That is, I have Nvim-R development version installed and gVim that runs Vim version 8.0.586 (I working in Windows 10 64bits). Whenever I hit "\rf" the R console opens in a separate window instead of embedded within gVim. Is there a way to have it embedded in gVim?

PS: should I put a separate issue from this one?

**Comment by jalvesaq** [comment]
Nvim-R now requires either Vim >= 8.0.0910 or Neovim to run R in a split window.

**Comment by LouisAsh** [comment]
Oh, it means that it does not run in a split window in gVim anymore? That is really really sad. Is it possible, by any chance, to get an older commit of Nvim-R that still is able to do so in gVim?

**Comment by jalvesaq** [comment]
It means that you should upgrade Vim. The download page of vim.org has a link to https://github.com/vim/vim-win32-installer/releases

**Comment by LouisAsh** [comment]
Oh, I see, I mis-read the version numbering as if it was prior to mine. Now I updated and it works properly. Sorry! (and thanks)

**Comment by research41** [comment]
system: window 10  x64
vim:       8.0.1071
nvim-r:  development version "git clone https://github.com/jalvesaq/Nvim-R.git"

error to install nvim-com
<img width="945" alt="20170909161336" src="https://user-images.githubusercontent.com/27892267/30243597-189ab3e0-957b-11e7-940f-dbace15c7acd.png">

specifically, the error is in " invalid multibyte character in parser".  my local language is cp936.
am I missing something?

**Comment by research41** [comment]
beside, each time I use gvim to open a *.R file, I have to confirm many times on command line. like follwing:
<img width="576" alt="20170909162831" src="https://user-images.githubusercontent.com/27892267/30243636-4a517b70-957c-11e7-8094-0cb2a04b4c48.png">

is there any walkaround?

**Comment by jalvesaq** [comment]
I do not have to press Enter to close console windows: when using GVim, these windows pop up and close automatically, and when using Neovim no window pops up.
Nvimcom builds fine in my system. So, I am sorry, but I cannot reproduce the bugs and, consequently, I do not know how to fix them.

**Comment by research41** [comment]
the console pop up is caused by setting gvim's default console as ConEmu, so If I remove this setting, the problem disappears.

**Comment by erw7** [comment]
After c924024, the same error will occur in the build of Nvimcom even in my environment(my local language is cp932.). I think that the problem will be reproduced in an environment where `l10n_info()$MBCS` is true. Does the problem reappear if `Sys.setlocale (category='LC_ALL', locale='Japanese')` is set in .Rprofile?
I think the cause is because `‘` (U+2018), `’`(U+2019), `“`(U+201C), `”`(U+201D) and `•`(U+2022?) are included in [nvim.bol.R#L195-L212](https://github.com/jalvesaq/Nvim-R/blob/master/R/nvimcom/R/nvim.bol.R#L195-L212).
Can you specify `Encoding: UTF-8` for DESCRIPTION file or not to use those characters?

**Comment by jalvesaq** [comment]
@erw7 I replaced the non ascii characters with `\uXXXX` code. Does it work now?

**Comment by research41** [comment]
I try the latest version, it still reports error!
![default](https://user-images.githubusercontent.com/27892267/31300999-e7da32a8-aac4-11e7-920c-a44c03e38111.png)

**Comment by jalvesaq** [comment]
It seems that the output of `R --slave -e 'cat(Sys.info()[[1]])'` is more than "Windows". Do you have any code producing extra output, like "World", the date, "Goodbye" and the date again in your .Rprofile?

**Comment by research41** [comment]
@jalvesaq   It works now.  
after I comment out `cat("\nWelcome R World", date(), "\n\n")`   `cat("\nGoodbye at ", date(), "\n")`  in my .Rprofile. 
thank you very much!

**Comment by erw7** [comment]
@jalvesaq  Yes, it is now built without any problems. Thanks.

**Comment by jalvesaq** [comment]
@research41 and @erw7  Thanks for the feedback!
