### ISSUE TITLE
Keep R tmux pane open after closing R

### ISSUE THREAD

**Issue by tgirke** [jalvesaq/Nvim-R#229]
Hi Jakson: 

I am trying to upgrade my outdated `vim-r/tmux` working habits to the new `nvim-r/tmux`. Things are working great so far. Thanks for all the useful upgrades!

One important detail I was not able to figure out, is how to keep a tmux pane open that runs a connected R session when closing R in that pane. With the default settings (below) from the [manual](https://raw.githubusercontent.com/jalvesaq/Nvim-R/master/doc/Nvim-R.txt) the R pane always closes after executing `q()`. 

```
let R_in_buffer = 0
let R_applescript = 0
let R_tmux_split = 1
```

The setting `R_close_term = 0` seems to be specific to the built-in terminal emulator. With the older `vim-r` it was possible to achieve this behavior with `let vimrplugin_restart = 1`.

Thomas

**Comment by jalvesaq** [comment]
Nvim-R runs the command `tmux split-window`... Is there a Tmux option to prevent the pane being closed when R quits?

**Comment by jalvesaq** [comment]
I have found the command: `tmux set remain-on-exit on`. If Nvim-R runs this command right after starting R, its pane will remain open, with the message "Pane is dead" at its bottom. Then, you would have to kill it manually with `CTRL-A :kill-pane`. Is that what you want?

**Comment by jalvesaq** [comment]
Note: the `remain-on-exit` command will affect the Vim pane too.

**Comment by jalvesaq** [comment]
To see how it works, please, run in R:
```r
system("tmux set remain-on-exit on")
```

**Comment by tgirke** [comment]
`system("tmux set remain-on-exit on")` freezes the pane and gives a `lost server` message in the nvim pane. In the past it was possible to close R and get a shell back. This way one could continue to send commands to the shell or a fresh R session, e.g. running on different computer node or server.

**Comment by jalvesaq** [comment]
I don't get the lost server message here, but I thought that you wanted to see some kind of error message output by R when quitting. I removed the option to have the shell running after R because the communication between Neovim/Vim and R is complete only if R is started by Neovim/Vim.

Did you read the section `Nvim-R-remote`?

**Comment by jalvesaq** [comment]
What is your tmux version? I'm running Tmux 2.3.

**Comment by tgirke** [comment]
I had tmux 2.0.1 installed. Now I upgraded to tmux 2.3 but this didn't change anything noticeable. Specifically, I open a (1) *.R file with nvim within a tmux session; (2) initialize a connected R pane; (3) execute in R `system("tmux set remain-on-exit on")`; (4) close R with `R()`. The latter gives a dead pane message that can be killed with tmux command kill-pane. Only if try to send some lines of R from the still open nvim pane then I get the lost-server message and the entire terminal/tmux session freezes. To get out of this sate, I have to close the terminal and open a new one. 

I read the Nvim-R-remote session but it does not specifically address how to get a shell back when closing an R session. Since I often use this environment for teaching classes in R (e.g. [here](https://goo.gl/ho3Mtt)) I would like to make it as easy as possible for the students. 

BTW: let's say I would run R in the built-in terminal emulator instead of a tmux pane, how can I switch the (cursor) scope from nvim to the R session and back to perform temporarily some work directly in the R console? Somehow I couldn't find how to do this in the manual.

**Comment by jalvesaq** [comment]
I guess that in step 4 you mean to close R with `q()`...

There is no easy way to get a shell back after closing R because there was no shell open before starting it. The Vim-R-plugin used to start the shell and, then, start R, but Nvim-R does not do this. Anyway, the complicated procedure that might work is:

1. Put `let R_in_buffer=0` and `let R_tmux_split=1` in the vimrc or init.vim.
2. Start editing an R file within a tmux session.
3. Start R with `\rf`(where `\` is the local leader).
4. Run `system("tmux set remain-on-exit on")` in R.
5. Quit R with `q()`.
6. Start the shell in the dead pane with the commands `CTRL-A` and `:respawn-pane bash`.
7. Manually start R in the new shell.

If you are using R in a built-in terminal emulator, you might use `CTRL-w w` to switch from one window to another. Please, see the tips in section 6.1 of Nvim-R documentation.

**Comment by tgirke** [comment]
Your suggestion (steps 1-7) do the trick to close R and then get a shell back while code sending from the nvim pane remains active. Thanks a lot! It is a bit more complicated than under the old Vim-R-plugin but perhaps for teaching I should switch to using R in the built-in terminal emulator anyways since it is easier for beginners to learn. 

Also, sorry for missing that the built-in terminal emulator behaves like a vim split. This one also supports various full terminal (zoom) views as it is possible with tmux panes, e.g. via `:tab sp`. Very useful! 

That should get me started. Feel free to close this issue thread.

**Comment by jalvesaq** [comment]
I'm closing the issue. Thanks for your feedback!
