### ISSUE TITLE
Nvim-R compatible with vim?

### ISSUE THREAD

**Issue by peidong** [jalvesaq/Nvim-R#25]
I am confused that I am now using traditional vim 7.4, but this plugin says it is compatible with neovim. Can I use this plugin with vim? Thank you!

**Comment by jalvesaq** [comment]
No, you can't. You have to use either
  - Vim + Vim-R+plugin + vimcom or
  - Neovim + Nvim-R + nvimcom

Reason: The communication from R to Vim depends on Vim's 'clientserver' feature, that is, X11 API (Linux), Windows API (Windows) and the equivalent Mac API (Mac OS X). Neovim does not have the 'clientserver' feature, but it does have something more flexible and powerful (job control) which I use to establish the communication from R to Neovim.

Both Vim-R-plugin and Nvim-R have the same features. Whenever I fix a bug or develop something new in one of them I port the changes to the other. Nvim-R is slightly better than the Vim-R-plugin because:

  - Neovim updates the syntax highlight immediately after a library is loaded in R (you have to move the cursor in Vim).
  - In some circumstances, there is a delay in the Object Browser update in Vim (when using GVim on Linux, for example). In Neovim, the Object Browser update always happens immediately after a command is processed by R.
  - We have the option of running R in a Neovim buffer, which makes the navigation from Neovim to R and vice-versa and copying and pasting easier than using Tmux commands.
  - Neovim is more stable than Vim (see https://github.com/jcfaria/Vim-R-plugin/issues/189 and https://github.com/jcfaria/Vim-R-plugin/issues/168).

**Comment by jalvesaq** [comment]
Nvim-R now is compatible with both Vim and Neovim.
