### ISSUE TITLE
new skim instance on recompile

### ISSUE THREAD

**Issue by ghost** [jalvesaq/Nvim-R#26]
Using Skim on OSX, with `let R_openpdf = 1`, every time I recompile, it spawns a new instance of Skim. Changing this value to 0 prevents Skim from being opened at all, so it works as expected in that regard.

**Comment by jalvesaq** [comment]
We may have to wait until someone else fixes this because I don't have access to any OS X. Currently, the plugin runs the following command:

```
/Applications/Skim.app/Contents/MacOS/Skim file.pdf
```

Does Skim have an option to reuse a running instance if the PDF is already open? If not, how can we know that the PDF is already open?

On Linux, the plugin keeps track of Zathura's PID and uses `wmctrl` to check if the Zathura instance displaying the PDF is still running before starting a new Zathura instance.

**Comment by mnosefish** [comment]
I can't seem to find any reference to that feature. I'll keep looking for a workaround. Perhaps if I made a keymap to just recompile without Skim. Unfortunately, I don't know enough about the guts of OSX to attempt a proper fix.

**Comment by jalvesaq** [comment]
If you put `let R_openpdf = 1` in your `init.vim`, the plugin should open Skim just once, and not every time the PDF is recompiled. There is some information about reloading updated PDF files here: http://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/

**Comment by mnosefish** [comment]
I do have that option set that way, but the behavior persists. Thanks for the info; I'll keep looking into it.

**Comment by jalvesaq** [comment]
`R_opendf = 1` now works as expected. I fixed the bug (https://github.com/jalvesaq/Nvim-R/commit/63b737c97a37508d7744b8bd05eb4f6c36d57add).

If someone could write an AppleScript to bring Skim window to the foreground, I could add the script to Nvim-R. This link might be useful: http://stackoverflow.com/questions/13173514/applescript-bring-window-to-foreground
