### ISSUE TITLE
Choose existing tmux pane?

### ISSUE THREAD

**Issue by meriops** [jalvesaq/Nvim-R#284]
When opening R in tmux, would there be a way to choose an existing tmux pane, rather than to create a new pane by default?

**Comment by jalvesaq** [comment]
No, I'm sorry. It would be necessary to create an option for this, and I'm not going to do this because:

1. Running R in a Tmux pane is no longer officially supported. I did not remove this feature because it is harmless (I don't have to spend time with it because it has no known bug). Note that Tmux is listed as Nvim-R dependency only if the user wants to run R in an external terminal emulator, and the explanation on how to use Tmux is in the "FAQ and tips" section.

2. It would be hard to guess what pane should be used.

Anyway, why do you want to do this? Perhaps there is another way of achieving what you want.

**Comment by meriops** [comment]
Jakson, fair enough. Regarding 2.: it would not be guessing, but rather passing it the pane number as an argument (they are numbered as window:pane by default, aren't they?). 
Anyway, I would like to do that because I usually start up with a tmux session coming up with my terminal, with pre-defined panes. I like to have my (R) script on the right of the screen and the R console on the top left. Right now, when opening R in tmux from within neovim, it creates a new tmux pane on the right, under neovim and my R script. Sure, I can move it around with tmux shortcuts but it's suboptimal. I'm sure there's a  more clever way to achieve that but I haven't figured it out...

**Comment by jalvesaq** [comment]
I forgot the main reason for what you want not being so easy to implement. Please, read section 5.5 of Nvim-R documentation. It would be necessary to call R with about five environment variables prefixed to the command.

**Comment by jalvesaq** [comment]
If you run R in a Vim/Neovim buffer, it would not split the tmux window, and you can control whether the Vim/Neovim window will be either vertically or horizontally with `R_rconsole_height`, `R_rconsole_width` and `R_min_editor_width`. But there is no option to start R on the left. I could add the options `R_top` and `R_left` for this.

**Comment by meriops** [comment]
It's a very specific use case... which is probably not worth implementing. I can always move the panes around after opening them. But thanks for your reply anyway. Keep up the good work!

**Comment by jalvesaq** [comment]
Looking at Vim documentation I noted that `R_top` and `R_left` are unnecessary because Vim and Neovim already have the options 'splitbelow' and 'splitright'. Regarding tmux, you may try to run a tmux command by setting `R_after_start`, perhaps the `move-pane` command.
I'm closing the issue...
