### ISSUE TITLE
Force-ubdate/rebuild the highlighting cache

### ISSUE THREAD

**Issue by ashiklom** [jalvesaq/Nvim-R#289]
Is there a way to force Nvim-R to rebuild its highlighting list?

While actively developing packages (and making repeat calls to `devtools::document`, `devtools::install`, `devtools::load_all`), it seems that Nvim-R likes to stick to older versions of packages I'm actively working for its highlighting cache.

For instance, if I change the name of a function `my_function` to `my_function2`, even after re-installing the package and restarting R, `my_function` is highlighted but `my_function2` is not.

On a different but possibly related note, even for installed CRAN packages, I often need to call `library(packagename)` two or more times before Nvim-R re-builds its highlighting cache.

And, on another different, but also related note, it would be _really_ cool if Nvim-R's highlighting was smart enough to recognize functions in the global environment, as well as those imported individually by using, for instance, the [import](https://cran.r-project.org/web/packages/import/vignettes/import.html) package.

All of this works fine for completion, so it seems that that list is being updated more immediately than the highlighting list. Perhaps this is a vim/neovim problem and not a Nvim-R problem?

**Comment by jalvesaq** [comment]
1. You have two options:

    1. Delete the file `~/.cache/Nvim-R/omnls_mypackage_X.Y.Z` where `X.Y.Z` is the package's version number.

    2. Increase the version number of the package whenever you want the list rebuilt. In the example above, you could add a fourth (and temporary) minor version number to `mypackage` during the development stage.

2. I have never noted problems with the highlighting. It always happens immediately after the package is loaded. However, if the package has changed and the version number remains the same (because you are actively developing it) the highlighting script will not be regenerated. And even if it is regenerated, you would have to restart Vim/Neovim because Nvim-R remembers the names of packages that already have had their functions highlighted and do not source the highlighting script again (`~/.cache/Nvim-R/fun_mypackage_X.Y.Z`).

3. It's possible to implement this feature (highlighting function from `.GlobalEnv`). Please, open an issue for this feature request, so I do not forget it.

4. You are right. As explained in item 2, the highlighting happens only once for each Vim/Neovim session. It would be necessary to clear the highlighting commands of a function before running the new commands, and Nvim-R does not do this.

**Comment by ashiklom** [comment]
Thanks for the info! Closing this issue, but see #291 about highlighting from the global environment.
