### ISSUE TITLE
Refreshing the html document instead of opening a new one

### ISSUE THREAD

**Issue by itissid** [jalvesaq/Nvim-R#290]
*switched from screen to tmux and it was good...*

But onto my idea... The `R_openhtml` option opens up a new HTML document in a chrome tab every time. It would be great if somehow it could just refresh the old window. But I don't see a good clean way of doing this with just the browser, though I am not sure. Perhaps something with an API like an electronjs browser window might work better as nvimR can communicate with it.

Also I don't know if I should move to NyaoVim just yet. Maybe you have a quick suggestion that can just work and I can try coding it up?

**Comment by itissid** [comment]
Actually the argument for an electron app just for the purposes of refreshing the window seems overkill. So maybe just a refresh solution for now might be ok.

On a side note a worthy goal is to have a more sophisticated electron app that can construct the markdown incrementally or perhaps only render the chunks that change. Perhaps something with Polymer components that can update specific chunks of the Rmd file as they change.

**Comment by jalvesaq** [comment]
The use of NyaoVim seems to be a good way of developing Rmd scripts, but I don't have time to work on this.
The easiest way would be if the web browser accepted a command to refresh a tab, but I think this command does not exist. I will see if I can do something with the suggestions from: https://unix.stackexchange.com/questions/37258/refresh-reload-active-browser-tab-from-command-line

**Comment by itissid** [comment]
@jalvesaq So I installed a simple chrome [extension](https://chrome.google.com/webstore/detail/super-auto-refresh/kkhjakkgopekjlempoplnjclgedabddk?hl=en) that refreshes the page, What might just be good for starters is a option to the `\kh` command that toggles the R_openhtml switch. That way once the page is opened, I can use \kh to generate it again and not have it open in a new browser window.

**Comment by jalvesaq** [comment]
The extension claims to "Auto refresh (reload) pages, on a selected interval". This is not the ideal solution because you will either see an outdated page for some time or get the page reloaded while you are reading it.

**Comment by jalvesaq** [comment]
I developed a solution for systems running the X server (Linux, for example). Please, see the documentation on `R_openhtml`. The application `xdotool` is required to send the `F5` key to the browser. I'm sure that we can get the same result with AppleScript on Mac OS X, but someone would have to translate these two commands:
```
xdotool search --name winname windowactivate --sync
xdotool search --name winname key --clearmodifiers F5
```
where `winname` is the document title and `F5` is the shortcut to reload the page. The first command brings the browser window to the foreground, and the second one sends the `F5` key. Both Firefox and Google Chrome add the page title to the window title. That is why `winname` is the document title.

**Comment by itissid** [comment]
thanks for developing this. But it still [seems](https://github.com/jalvesaq/Nvim-R/commit/0caf5f29974dc935b511d7de7a3002a4dd2d0a63#diff-223ee580010d2b13932f776c5489e955R2293) that the `RLoadHTML` function is still returning prematurely when `R_openhtml=1` before it gets to the `xdotool` command. Is that intentional?

**Comment by jalvesaq** [comment]
The meanings of different values of `R_openhtml` are:

0: Never open the html.
1: Always open the html.
2: Use xdotool to decide between opening the html and reloading the page.

The default value of `R_openhtml` is `0` if `xdotool` is not installed and `2` if it is installed.

> Also I don't have a lot of knowledge about X related tools. But since I am on a Mac I assume this requires me to be "running" some sort of X related display system?

I guess this is not a good option because you would have to run an X based browser. The better option is to write a pull request replacing `xdotool` commands with AppleScript commands in the three `system()` calls in the code below:

```
    if g:rplugin_is_darwin
        let winnum = system('xdotool search --name ' . winname)
        let g:rplugin_debug_info['RefreshHTML'] = [a:fullpath, a:browser, winname, winnum]
        if winnum == ''
            if has('nvim')
                call jobstart([brwsr, a:fullpath], {'detach': 1})
            else
                call job_start([brwsr, a:fullpath])
            endif
        else
            call system('xdotool search --name ' . winname . ' windowactivate --sync')
            call system('xdotool search --name ' . winname . ' key --clearmodifiers ' . g:R_html_reload_key)
        endif
        return
    endif
```
You could try the AppleScript commands in a separate terminal emulator and when you get them working either write a pull request or paste them here.

> thanks for developing this. But it still seems that the RLoadHTML function is still returning prematurely when R_openhtml=1 before it gets to the xdotool command. Is that intentional?

Because your browser is not an X application, xdotool cannot find it (line 2 of the code above). Consequently, the html is opened again (either line 6 or 8).

**Comment by itissid** [comment]
hey I created a PoC https://github.com/jalvesaq/Nvim-R/pull/298. There is just one little kink with getting safari to open a window. Chrome works ok for me. Let me know if you want me to add additional documentation.

**Comment by jalvesaq** [comment]
@itissid I reached the conclusion that Nvim-R should not take care of refreshing the browser because each browser has a different behavior in each system and it would be too complicated to maintain the support for every combination of browser and system. So, I'm going to remove the option `R_openhtml=2` and add to the documentation tips on how to create the refresh script and change the `options("browser")` in the `~/.Rprofile`.

**Comment by mikemc** [comment]
One simple manual approach I've found useful is to run `servr::httw()` on the relevant containing directory, or file, using [Yihui's servr R package](https://github.com/yihui/servr)
