### ISSUE TITLE
Windows - neovim-qt: tmp files can not be opened if R file path starts with double backslash

### ISSUE THREAD

**Issue by jranke** [jalvesaq/Nvim-R#296]
Nvim-R in neovim-qt on Windows 10 works fine for local files. Also, when I edit an R file on a network share connected to a drive letter (e.g. `Z:\test.R`) Nvim-R works fine. However, when I access the same file via the network environment so its path is `\\SERVER\share\test.vim` I get 

```
Error detected while processing function RonJobStdout[7]..RSetMyPort[4]..FinishStartingR:
line   15:
E482: Can't open file C:/Users/my_user/AppData/Local/Temp/NvimR-my_user/GlobalEnvList_"\\SERVER\share" for writing: no such file or directory
```

After pressing enter for each time this error occurs, R is started in the internal buffer. But when I try to send code to R, I get

```
Error: Could not write to 'C:/Users/my_user/AppData/Local/Temp/Nvim-R-my_user/libnames_"\\SERVER\share"'. [nvimcom]
```

Working with the same path works as expected with gvim: R is started in an internal buffer and communicates with vim.

**Comment by jalvesaq** [comment]
I don't have a windows network to replicate the issue, but I've just added an alternative way of getting both `$NVIMR_ID` and `$NVIMR_SECRET`: https://github.com/jalvesaq/Nvim-R/commit/f7d627497ff62853e72016160e67a972ac38e206

**Comment by jranke** [comment]
Thanks for your quick reply! I just updated Nvim-R and tried again, but I get exactly the same error...

**Comment by jranke** [comment]
What is the function of the GlobalEnvList_* file in the temporary directory?

**Comment by jalvesaq** [comment]
The file `GlobalEnvList_$NVIMR_ID` is the list of objects in R's workspace. It is used for omni completion.

**Comment by jalvesaq** [comment]
Maybe it will work after the last commit, but with less safe `$NVIMR_ID` and `$NVIMR_SECRET`, based on current time:
```
let $NVIMR_ID = strftime('%m%d%Y%M%S%H')
let $NVIMR_SECRET = strftime('%m%H%M%d%Y%S')
```

**Comment by jranke** [comment]
With the latest commit I get (with nvim-qt):

```
Using insecure communication with R due to failure to get random numbers from nclientserver: "\\SERVER\share\test.R"
```

and some more text telling me that CMD.EXE is started at this path and that UNC paths are not supported, so the (corresponding?) Windows directory is used.

Then I have to press ENTER to continue. When I do so, the view is split and a terminal is opened. However, I get some message (about UNC paths not being supported and that the Windows directory is used) above the R starting message, and the terminal does not scroll automatically to show me the latest R commands and outputs.

Meanwhile I have switched back to using current gvim under Windows, which now works nicely with the built-in terminal support that I had not tested before.

**Comment by jalvesaq** [comment]
Normal messages would quickly disappear because R is being started and the window is being split. That is why you are forced to press ENTER after the message is displayed. And I believe that it is important to inform users that it is not impossible to someone in the same network to execute commands through TCP messages sent to either Nvim-R (via the nclientserver) or R (via nvimcom).

The scroll issue was introduced by https://github.com/jalvesaq/Nvim-R/commit/550151ba2125c8cd108f843faa8fae8cb662f818 and probably is fixed by https://github.com/jalvesaq/Nvim-R/commit/8a88e4c63d6ddcebe19038cc70158ec6d8b441f9

However, note that now that Nvim-R does not go to the Terminal window to get its width before sending commands to R, the terminal will stop automatically scrolling if you backscroll it, which is considered a feature. See: https://github.com/neovim/neovim/issues/2636

Regarding the original issue that you reported, I still don't know how to fix it. I think it is a Neovim bug, but probably I could find a workaround if I could replicate the it.

**Comment by jranke** [comment]
Thanks for your time. After updating to the latest revision, I can actually work with nvim-qt on an UNC path!

I think it is totally correct to let the user acknowledge the message about the insecure connection. I was actually wondering why, there is an additional message that is also printed in the terminal window before the R startup message is printed. I just did not realise that this message must originate from the operating system, because it is written in German!

If I translate it to English, it looks like this:

```
"\\SERVER\share"
CMD.EXE was started with the above path as working directory.
UNC paths are not supported.
Instead, the Windows directory is used as working directory.

R version ...
...
```

It seems this is simply related to the way nvim-qt starts its terminal, as opposed to how gvim starts its terminal in this case. The working directory in R running in that nvim terminal is nevertheless 

```
> getwd()
[1] "\\\\SERVER/share"
```

**Comment by jalvesaq** [comment]
I could replicate the issue. I right clicked on a directory and shared it through the local network. Then I could access the file on my own laptop from the network. The problem is that `system()` runs `cmd.exe`, and `cmd.exe` works, but outputs that warning which gets mixed with the `nclientserver` output. One simple solution is to clean the output if `getcwd() =~ '^\\\\'` but it would be better to replace `system()` with something else, perhaps a job, although we don't need an asynchronous job here.

**Comment by jalvesaq** [comment]
In a quick test, it worked for me after https://github.com/jalvesaq/Nvim-R/commit/dc4974e7bf4309618c99af7a92da057f2e208f9c

**Comment by jranke** [comment]
Yes, working over here as well, therefore closing the issue. Thanks a lot. Now get to choose between neovim (which I use on Linux) and gvim which I currently use on Windows.

BTW, I should file an issue on neovim-qt as well, as I noticed that I get the same messages e.g. when I press `D` after a `PlugUpdate` when editing a file on a UNC path. I am just not really convinced that I need neovim-qt on windows when there is gvim with terminal support unaffected by this bug.

**Comment by jalvesaq** [comment]
GVim is more stable than Neovim on Windows, but Neovim has the advantage of syntax highlighting the output.

**Comment by jranke** [comment]
Ah, that makes sense. Thanks again!
