### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by romagnolid** [jalvesaq/Nvim-R#314]
Hi, after the last update when pressing \rh to show the documentation it says "Unable to get dev documentation."

**Comment by jalvesaq** [comment]
Perhaps either @nacnudus or @ashiklom could help with this issue because I don't use devtools (please, see https://github.com/jalvesaq/Nvim-R/issues/146).

**Comment by ashiklom** [comment]
I _think_ this is because you don't have the `pkgload` package. It's not on CRAN yet, but probably will be once the current development version of `devtools` gets on CRAN as well.

The easiest fix is probably to install `pkgload` from GitHub: `devtools::install_github("r-lib/pkgload")`.

@jalvesaq Perhaps https://github.com/jalvesaq/Nvim-R/commit/14a9d196d88060e90e6aa296ca6c92447e49ed3b was a bit premature, since it is only relevant to development versions of `devtools` and `pkgload`. If you want, you could revert that commit for now and un-revert it later.

**Comment by jalvesaq** [comment]
I added a check of pkgload::dev_help existence that should avoid the error (not tested because I don't have devtools installed). @nacnudus or @ashiklom please feel free to further improve the code if you think in a better solution.

**Comment by romagnolid** [comment]
Sorry, but it seems it's not sufficient. I manually installed the packages as suggested by @ashiklom and updated Nvim-R but it gives the same error. 
Anyway calling `help(<something>)` from the R terminal (inside vim) correctly open the documentation in a new tab (accordingly to my vimrc settings). So it's just the shortcut that's not working.

**Comment by jalvesaq** [comment]
Since I can't fix the issue, I prefer to wait for a pull request...

**Comment by romagnolid** [comment]
As soon as I learn vimscript I'll try to propose a solution
