### ISSUE TITLE
Keep getting 'Error object not found' in RStudio when im trying to read a list of .csv files

### ISSUE THREAD

**Issue by maruengine** [jalvesaq/Nvim-R#319]
I am trying to read a file in Rstudio that contains a list of .csv files. It was zipped so i unzipped it in my 'Downloads' directory and the folder  'specdata' was automatically created containing all the .csv files.

I opened RStudio and changed my working directory to 'Downloads' and still i cant read the folder and keep getting the error object not found. Cant figure out what im doing wrong. I am new to R so any help will be appreciated.

what i did was:      setwd("C:/Users/maryk/downloads")
and then             list.files(specdata, full.names=TRUE)[1:332]
 and i get that error : ''Error in list.files(specdata, full.names = TRUE) : 
  object 'specdata' not [found"](url)
![screenshot 55](https://user-images.githubusercontent.com/37640324/38724036-17d06412-3f14-11e8-99ef-71cae738f550.png)

**Comment by jalvesaq** [comment]
`specdata` should be between quotation marks, otherwise, R will look for an object called `specdata` which does not exist. So, your code should be:
```r
list.files("specdata", full.names = TRUE)
```
This is unnecessarily complex, but it would work too:
```r
x <- "specdata"
list.files(x, full.names = TRUE)
```
But note that here is a place for reporting issues with Nvim-R. You should have posted your question in a mailing list or forum dedicated to help R users.
