### ISSUE TITLE
vi(func) from R code window will render the R terminal useless

### ISSUE THREAD

**Issue by randomizedthinking** [jalvesaq/Nvim-R#32]
When using Nvim-R, if type in a `vi` command in the R terminal to check the definition of a function, like

~~~
vi(ls)
~~~

then we can exit it by pressing *ZZ*. But if it is launched from the R code window, then basically I found we would be stuck. If pressing *ZZ* in the so-called terminal window now, it would close the whole terminal rather than the interior vi.

It might not be a bug.  Understand it is a nasty thing: a vi inside vi. Any suggestions? Thanks!

**Comment by jalvesaq** [comment]
I didn't know about the command ZZ, but now I know and I confirm the issue. Note that it only happens if you enter Insert mode in the nested vim. Then, you are trapped in Insert mode there because when you press `<Esc>` you leave TERMINAL mode in the terminal and, consequently, the nested vim can no longer receive the `<Esc>` key. The issue happens regardless of the command being typed in the Terminal or being sent from the script buffer. The solution is to put in your init.vim:

```vim
let R_esc_term = 0
```

Please, see `:h R_esc_term`.

**Comment by randomizedthinking** [comment]
Thanks for the prompt reply!

`R_esc_term` does not solve the issue at least not for my case: when in the insert mode inside the terminal, Esc still simply turns the terminal to normal mode but not the nvim inside the terminal. I found the following method works:

~~~
tnoremap <F7> <Esc>
~~~

In other words, `F7` can be used to escape the nvim inside the terminal at terminal mode.

**Comment by jalvesaq** [comment]
Perhaps you already have put this in your vimrc:
```vim
:tnoremap <Esc> <C-\><C-n>
```
This is what `R_esc_term = 1` does.

**Comment by jalvesaq** [comment]
I committed some changes to both Nvim-R and nvimcom and now, if `R_esc_term` = 1, the R function `edit()` will make Neovim to edit the object in a new tab. So, you should have no problem if using `edit()` instead of `vi()`. The plugin's documentation has more details.

**Comment by jalvesaq** [comment]
You can use vi() again. The object will be edited in a Neovim tab.
