### ISSUE TITLE
knit with leader+k+p would not update child Rnw change 

### ISSUE THREAD

**Issue by smilesun** [jalvesaq/Nvim-R#347]
reproducible example:
hi.Rnw:
```
% vim:ft=tex:
%

\documentclass[12pt]{article}

\title{
	hi
}
\author{
	sunxd --- \texttt{sunxd@sunxd-ThinkPad-T460s}
}
\begin{document}
\maketitle

Hallo Welt!
<<child="child.Rnw">>=
@
\end{document}
```

child.Rnw:

`Hi, I am a child.`

Now if you change child.Rnw to Hi I am not a child. 

Then you execute leader+k+p, the pdf is still the same.

**Comment by jalvesaq** [comment]
Thanks for reporting the issue. It should be fixed now.

**Comment by jalvesaq** [comment]
Sorry, I commited the changes in the bibcompl branch...

**Comment by jalvesaq** [comment]
It should be OK now...

**Comment by jalvesaq** [comment]
Please, reopen the issue if it is not fixed.

**Comment by jalvesaq** [comment]
I can't replicate the issue. When I change the child, save it, and generate the pdf with `<LocalLeader>kp` the pdf is correctly updated. But note that the child isn't automatically saved when you press `<LocalLeader>kp`. You have to save it manually because only the master Rnoweb document is automatically saved before compiling the pdf.

**Comment by smilesun** [comment]
well, sometime it occurs with very complicated example which I can not post here but most of the time it works. Let me see if I could generate another reproducible example
