### ISSUE TITLE
Behavior of the various resizing commands (Ctrl-w)

### ISSUE THREAD

**Issue by tvatter** [jalvesaq/Nvim-R#390]
Hi,

I noticed that, when an R console is open (e.g. after calling `leader-rf`), the commands `Ctrl-w +`, `Ctrl-w -`, `Ctrl-w >`,  and `Ctrl-w <` still work as expected.

However, `Ctrl-w =` equalizes only the height but not the width of all windows.

Is it supposed to be the case? Is there any way to change this behavior?

**Comment by jalvesaq** [comment]
The function that starts R in a Vim/Neovim buffer includes the command `set winfixwidth`. See https://github.com/jalvesaq/Nvim-R/issues/313#issuecomment-381257816
Maybe <kbd>CTRL</kbd>+<kbd>W</kbd><kbd>=</kbd> should not equalize the height too.
Anyway, if your prefer `winfixwidth` not being set, I can add an option for this.

**Comment by tvatter** [comment]
I understand, but then why are the commands `Ctrl-w +`, `Ctrl-w -`, `Ctrl-w >`,  and `Ctrl-w <` working as expected?

And yes, definitely, the option for this would be extremely useful (to me at least).

**Comment by jalvesaq** [comment]
The goal is to avoid automatic resizing of the R Console when the terminal is resized or when a Vim's window is split. I don't have an answer to your question because what `Ctrl-w` commands still work and what commands are disabled by `winfixwidth` is the result of a choice made by Vim developers.

I'm going to commit a change with a new option `R_buffer_opts`. Please, update the plugin and read the documentation on this new option.

**Comment by tvatter** [comment]
This works perfectly, thanks a lot!
