### ISSUE TITLE
Conflict with use of renv

### ISSUE THREAD

**Issue by statquant** [jalvesaq/Nvim-R#445]
For some reason when I use the new renv package the nvimcom package fails to load.
renv messes with the concept of library because it creates a project specific library.
Not sure what to do to be honnest
```
* Project '/home/auction_book_research' loaded. [renv 0.8.3] 
During startup - Warning messages:                                                          
1: In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :  
  there is no package called 'nvimcom'                                                      
2: package 'nvimcom' in options("defaultPackages") was not found                            
R>                                                                                          

```

**Comment by jalvesaq** [comment]
I'm sorry, but I don't use `renv`. Please, post here any solution that you find to help others with the same issue.

**Comment by statquant** [comment]
ok, can you give me more information on how nvimcom is loaded ?

**Comment by jalvesaq** [comment]
Nvim-R sets the environment variable `R_DEFAULT_PACKAGES`, including `nvimcom` in the list of packages to be loaded on R startup.

**Comment by grepinsight** [comment]
The issue is that you have to install nvimcom for a new renv

I solved this issue with the following command (assuming you are using a Vim-plug manager)

```
devtools::install("~/.vim/plugged/Nvim-R/R/nvimcom")
```

**Comment by jalvesaq** [comment]
Thanks for the feedback!

**Comment by statquant** [comment]
Sorry I am not sure I understand, where do I put this command? in which context? @grepinsight

**Comment by jalvesaq** [comment]
@statquant I suppose you have to run the command after R is started. You have to adjust the path to the `nvimcom` directory.

**Comment by vizowl** [comment]
Just adding my experience.

On a mac `devtools::install` doesn't work for me but `renv::install` does.

**Comment by AdrienLeGuillou** [comment]
I have another solution that does not involve installing `nvimcom` in the project library.

I created a folder `~/R/nvimcomlib` containing a link to the `nvimcom` library. Thus, I have `~/R/nvimcomlib/nvimcom` pointing to `~R/x86_64-pc-linux-gnu-library/4.0.0/nvimcom/`

Then in my ".Renviron" file I have

```
RENV_CONFIG_EXTERNAL_LIBRARIES="~/R/nvimcomlib"
```

this tells `renv` to use the "~/R/nvimcomlib/" folder to look for packages. This solution allows the `renv.lock` file to be completely independent of `nvimcom` and avoids loading the full user library as the folder contains only the link to the `nvimcom` folder. 

By using `.Renviron` instead of `.Rprofile`, this solution works even if the `renv::init()` was done without authorizing the users `.Rprofile` (recommended to guarantee reproducibility).

The only issue I have is that I will have to recreate the link when updating R. But it's a minor inconvenience I think.

**Comment by klmr** [comment]
@AdrienLeGuillou Did you get any trouble after updating nvimcom? Your solution worked for me until recently, but now I’m getting a message

> Error: package or namespace load failed for ‘nvimcom’:
>   .onAttach failed in attachNamespace() for 'nvimcom', details:
>   call: if (as.integer(getOption("nvimcom.lsenvtol")) < 10) options(nvimcom.lsenvtol = 10)
>   error: argument is of length zero

This message does not occur without renv (even though the option is in fact never set).

**Comment by chunyunma** [comment]
@AdrienLeGuillou 
I ran into the same problem recently and was very happy to see that others had already solved the problem.  I tried the solution you provided, but still got the message "package ‘nvimcom’ in options("defaultPackages") was not found" when I fired up R within neovim.

I am running on OSX Catalina. And instead of pointing the softlink to `nvimcom` installed via R, I routed it to `nvimcom` that came with Nvim-R: `/Users/chunyun/.local/share/nvim/plugged/Nvim-R/R/nvimcom/`.

I also tried to install `nvimcom` separately using R but found out that the package had been [deprecated](https://github.com/jalvesaq/nvimcom).

This is what I did when I tried your solution:

softlink to `nvimcom`
Add the directory in the local `.Renviron` file
`\rf` --- _fire up R within neovim_
`library(renv)`
`renv::init()` --- _`source("renv/activate.R")` was automatically added to `.Rprofile` after this step_
`\rq`, `\rf` to restart R within neovim --- _this is when I got the error message_

Do you happen to know what may be the reason for my error?

Thank you!
