### ISSUE TITLE
Nvim-R Colors on windows

### ISSUE THREAD

**Issue by blayz3r** [jalvesaq/Nvim-R#450]
This is more of a question, it looks like I can only see colors in the _**terminal normal mode**_ on windows (Vim proper). Any thoughts?

**No Color insert mode**
![image](https://user-images.githubusercontent.com/12205650/70265732-015b7f80-1769-11ea-9f72-5fa804f18957.png)

**Color Normal mode**
![image](https://user-images.githubusercontent.com/12205650/70265745-0e786e80-1769-11ea-9725-c700e52ebe37.png)

**Comment by jalvesaq** [comment]
Vim only supports "syntax" highlighting when not in Terminal mode. It's the same on both Linux and Windows. If you want colorized output, you have to use Neovim. On both Linux and Mac OSX, you can use [colorout](https://github.com/jalvesaq/colorout) to colorize R's output.

**Comment by blayz3r** [comment]
https://github.com/randy3k/radian solves the problem

**Comment by jalvesaq** [comment]
It seems that radian colorizes the input, not the output. It's the opposite of what Nvim-R does.

When editing R code, I want the code highlighted in the editor because colors make the edition easier, but I want the code monochromatic in the R Console because I want to focus on the output.

Radian is great to run R by itself, not called by Nvim-R. But even in this case I still want colorout colorizing the output.

**Comment by blayz3r** [comment]
It's not a replacement for colorout but it's a middle ground for windows. I mostly want to see errors in red.
