### ISSUE TITLE
Understanding nvimcom messages

### ISSUE THREAD

**Issue by bvz0325** [jalvesaq/Nvim-R#465]
I am beginning my journey with R and have a basic file for editing in vim. I setup nvim-r with vundle and opened a new *.R file in vim.

Setup:
OS = Linux
Vim = v8.2.148
R = v3.6.2

This file contains only very basic R commands, like:
`y <- c(1,2,3)`
`length(y)`

But after \rf and \aa, instead of outputting the result of length(y), I see only the following error message in the R console:
`nvimcom:::source.and.clean("/my/directory/file.r.tmp.R")`

Any ideas? Cheers!

**Comment by jalvesaq** [comment]
>  nvimcom:::source.and.clean("/my/directory/file.r.tmp.R")

This is not an error message. It is a command send from Nvim-R to R Console. A copy of your R script is created, sourced and deleted. Nvim-R does not send to R the command to source the original file to avoid saving it because the user might not want to save it at the moment.

If, in addition to sourcing the script, you want to see the output, the shortcut is `<LocalLeader>ao`.

**Comment by bvz0325** [comment]
Thanks for responding, I get it now!
