### ISSUE TITLE
Please, set the variable 'g:R_term_cmd' in your vimrc. (Ubuntu app on Windows)

### ISSUE THREAD

**Issue by joelwatsonfish** [jalvesaq/Nvim-R#484]
I hope this is the right place to ask.

I'm running NeoVim (v0.4.3)
on the Ubuntu App (Ubuntu 20.04 LTS (GNU/Linux 4.4.0-18362-Microsoft x86_64))
in Windows 10 Home (version 1909; 64 bit)

I believe I have the the plugin Nvim-R properly installed (via Vundle), however when I try to start Nvim-R from Neovim, I get the error:

`Please, set the variable 'g:R_term_cmd' in your vimrc.`

I'm not sure what to set it to, as I didn't have this problem when I installed on MacOS.  In my `~/.config/nvim/init.vim` file I tried adding the line

`let R_term = "nvim"`

but when I try to start up Nvim-R, it says

```
updating nvimcom
...
`"Terminal emulator" exited with status 1"
The package nvimcom wasn't loaded yet. Please, quit R and try again.
```

I'm not really sure what the issue is, but any suggestions would be appreciated.

**Comment by jalvesaq** [comment]
Try adding this to your `~/.config/init.vim`:

```
let R_in_buffer = 1
```

Or simply does not change the default value of `R_in_buffer` and R will run in a Neovim built-in terminal (a special buffer). Perhaps I should change the name of this variable to `R_builtin_term` or `R_extern_terminal` since the name `R_in_buffer` does not seem to be meaniful for most users.

**Comment by joelwatsonfish** [comment]
Sweet! It worked!  Thank you very much.  I had `R_in_buffer=0` with no comment as to why; maybe left over from when I used to use tmux with vim.  In any case it's working now.
