### ISSUE TITLE
Completion issues with neovim: E731: using Dictionary as a String

### ISSUE THREAD

**Issue by emanuelealiverti** [jalvesaq/Nvim-R#495]
Autocomplete issues after last update. I'm using neovim 0.4.3 release build, appimage version.
(also happens vith neovim 0.4.3 build from source)

Steps to reproduce:

**minimal.vimrc**

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
```

**test.r**
```R
x = rn
```

**Commands/Input**
`nvim -u minimal.vimrc test.r`.

When I try to complete something (for example `rn`, expected to open the completion menu with `rnorm` and `rnbinom`) with `<C-x><C-o>` I get the following error:

```vim
E731: using Dictionary as a String
E731: using Dictionary as a String
```
then, the popup window shows up. So it's not really buggy but still annoying.

**Comment by jalvesaq** [comment]
I can't replicate the issue even with your minimal vimrc, but my neovim version is  v0.5.0-532.

**Comment by emanuelealiverti** [comment]
I have updated nvim to the latest  v0.5.0-533-g5a9226c, compiled from source and everything works for me as well. It's probably a neovim issue, then. Sorry for not thinking about it.

**Comment by jalvesaq** [comment]
I installed Neovim from the Ubuntu repository and then I could look at the issue. The problem is that I added support for floating windows a few days after this change in Neovim: https://github.com/neovim/neovim/commit/c477b19bdca0cc57e08f5fb93f647767ea84dd3e

So, I didn't know that `user_data` should be a string just a few days ago.
