### ISSUE TITLE
Object browser not viewing variables with long names.

### ISSUE THREAD

**Issue by anasshe3sha3y** [jalvesaq/Nvim-R#504]
**Variables in a dataframe are not viewed if their names have too many characters.**

**In the image:** the original dataframe has 22 columns but only those with names less-than-70-characters-long are viewed
![2020-06-22-062603_484x254_scrot](https://user-images.githubusercontent.com/26515372/85249504-3785f580-b454-11ea-862a-4aa5ec5ad4f1.png)
and this also produces the same bug on my system:
```
data <- data.frame(aaa = c(1,2),
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = c(1,2))

```
Is it intended to work like that? If so, how can I force it to print all variables?

**Comment by jalvesaq** [comment]
It has a hardcoded limit of 64 characters. Objects with names bigger than that are skipped. I have guessed that most people would never use variable names so big and that they would add the attribute "label" to their variables instead. There are some functions that use the "label" attribute when printing tables and plotting figures.
It's better to have a size limit for the Object Browser. Otherwise, I would have to set more dynamically the size of the buffer that receives the data. Allocating memory is among the slowest operations in C and even more so for large chunks of data.
I will see what happens if I add some more call to `strlen()` to `nvimcom.c`...

**Comment by anasshe3sha3y** [comment]
>  I have guessed that most people would never use variable names so big and that they would add the attribute "label" to their variables instead.

Indeed, that is a more rational way to do it. In my case, importing data directly from survey programs (e.g. Google forms) as .csv stores the questions as variable names, and some of them are expected to be long.

> I will see what happens if I add some more call to `strlen()` to `nvimcom.c`...

That is great! I think the least confusing for users is to truncate the ends of very long names with dots like (What are the fr...), similar to what happens in the environment panel in RStudio, if that is a possible thing.

**Comment by jalvesaq** [comment]
While I don't fix the issue, you could try something like this:

```
nm <- colnames(dtfrm)
colnames(dtfrm) <- paste0("q", 1:ncol(dtfrm))
for(i in 1:ncol(dtfrm))
    attr(dtfrm[[i]], "label") <- nm[i]
rm(nm, i)
```

**Comment by jalvesaq** [comment]
I fixed the issue (truncate the name at byte 62) in the branch https://github.com/jalvesaq/Nvim-R/commit/ffcfe0a9de28474bd7b778184c229d1019b310ee

It would be good if you could try it before I merge it into the master branch.
If using [vim-plug](https://github.com/junegunn/vim-plug), it's easy:

```
Plug 'jalvesaq/Nvim-R', {'branch': 'faster_omnicompl'}
```

**Comment by anasshe3sha3y** [comment]
I tried it. It shows all 22 variables now, with all variables longer than 62 characters truncated.

![2020-06-24-010146_581x463_scrot](https://user-images.githubusercontent.com/26515372/85475707-d0348680-b5b6-11ea-95e0-12fc4380512b.png)

And wow thanks a lot for the superfast fix!

**Comment by jalvesaq** [comment]
The changes are now in master branch, and I will delete the `faster_omnicompl` branch soon.
