### ISSUE TITLE
Disabling jump to line with `browser()`

### ISSUE THREAD

**Issue by lyh970817** [jalvesaq/Nvim-R#507]
Is there a way to disable auto jump to browser() position?

**Comment by jalvesaq** [comment]
Not yet. I would have to add an option for that.

**Comment by jalvesaq** [comment]
Please, update the plugin and put in your vimrc:

```
let R_debug = 0
```

**Comment by nhejazi** [comment]
Hi @jalvesaq, thanks for the awesome work on this plugin over the years! After upgrading, I recently ran into this functionality, and it’s really been hurting my workflow — I rely on calls to `browser()` to enter the R debugger and usually work from there (so I use it all the time).

I’d really like to disable this functionality since skipping back to the line with the browser call is very annoying when I’m working through a long function call. I tried the fix in your comment but it doesn’t seem to change the behavior at all, even after updating the plugin. Is there something I’m missing here? If it’s important, I still use the Vim plugin with tmux integration (and I pull the latest version of that from this repo).

**Comment by jalvesaq** [comment]
Are you using the last released version? The `R_debug` option was added to the master branch of the git repository.

**Comment by nhejazi** [comment]
Thanks for the quick reply. This is a good point, I use [vim-plug](https://github.com/junegunn/vim-plug) and ran `:plugUpdate` so this may have pulled from a source other than the `master` branch. Would you recommend changing the source to always pull from that branch rather than release?

**Comment by jalvesaq** [comment]
Vim-plug will pull from the master branch, unless you add `, {'branch': 'stable'}`. I follow the convention of not adding new features, including new options, to the stable branch. However, since we can consider a bug the support for `debug()` without the option to disable it, I will add the option the the 'stable' branch too.

**Comment by jalvesaq** [comment]
The issue is now fixed in the stable branch too.

**Comment by nhejazi** [comment]
Great, thanks much for the quick fix and support on this.
