### ISSUE TITLE
nvimcom not loading on windows gVim

### ISSUE THREAD

**Issue by MashiroKinji** [jalvesaq/Nvim-R#51]
I has used neobundle to install Nvim-R and install RTools
version of R is 3.2.4, RTools is RTools33
but when i push C-X C-O  will appear " List is empty, Did you load nvimcom package? "
Is nvimcom automatically loaded ?

**Comment by jalvesaq** [comment]
The R package nvimcom should be loaded automatically because Nvim-R sets the value of `R_DEFAULT_PACKAGES` to `utils,grDevices,graphics,stats,methods,nvimcom`.

You can check in R whether `R_DEFAULT_PACKAGES` was set or not:
```r
Sys.getenv("R_DEFAULT_PACKAGES")
```
And whether nvimcom is loaded or not:
```r
search()
```

What is the output in GVim when you do in Normal mode after starting R?:
```vim
:messages
```

**Comment by MashiroKinji** [comment]
Thanks.
I find the question.
I don't run R by use Nvim-R command "\rf", I run R from windows cmd
and it make R_DEFAULT_PACKAGES is not read from Nvim-R

**Comment by jalvesaq** [comment]
Thanks for the feedback! Please, reopen the issue if you still have problems to get nvimcom loaded.
