### ISSUE TITLE
"R" exited with status 137

### ISSUE THREAD

**Issue by jimrothstein** [jalvesaq/Nvim-R#536]
Running a lengthy R function in neovim term (NVIM v0.4.3   ), nvim-R (v 0.9.14.1 )

R and nvim-R disappear, with error in neovim "R exited with status 13";  neovim seems fine.

Any ideas?  Thx.

**Comment by jalvesaq** [comment]
I'm sorry, but I have never had this issue, but if it is caused by Nvim-R it will by the nvimcom package which has code written in C. Could you run R under GDB? After installing gdb, you could put in your init.vim:

```
let R_args = ['--quiet', '--no-save', '-d', 'gdb']
```

When the prompt `(gdb)` appears, you have to press `r` to actually **run** R. After finishing the R session, you have to press `q` to **quit** GDB.

**Comment by jimrothstein** [comment]
Thx for quick response.    Will see if I get GDB debugger running.   Thx.

**Comment by jalvesaq** [comment]
Thanks for the feedback!
