### ISSUE TITLE
indentation should not indent Roxygen comments

### ISSUE THREAD

**Issue by dankelley** [jalvesaq/Nvim-R#560]
I may be doing things incorrectly, because I've been using vim mode for many years and therefore might have a messed-up `.vimrc` file, but what I'm finding is that Roxygen comments, which have `#'` as the first two characters on a line, get space added to the left when I indent.  Is there a setting that will avoid that?  I ask because I use indentation quite frequently, and every time, I have to do a `%s/^[ ]+#'/#'/` to fix the problem. Obviously, that's not hard to do, but it would be great if I could put something in my `~/.vimrc` to prevent my having to do that.

PS. Another thing I'd love would be if indentation would not break within a quoted string.

**Comment by kklot** [comment]
Can you try this

`:h si`

```
        When typing '#' as the first character in a new line, the indent for                                                     
        that line is removed, the '#' is put in the first column.  The indent                                                      
        is restored for the next line.  If you don't want this, use this
        mapping: ":inoremap # X^H#", where ^H is entered with CTRL-V CTRL-H.                                                       
        When using the ">>" command, lines starting with '#' are not shifted
        right.
```

**Comment by jalvesaq** [comment]
Nvim-R is being superseded by R.nvim, a new project that will be inaugurated in a week at the [R-nvim](https://github.com/R-nvim) organization.
Please, check out [tmp-Nvim-R](https://github.com/jalvesaq/tmp-R-Nvim) and help us to find the last remaining bugs before R.nvim inauguration.
When the project is officially started, you will be able to open issues there and request new features.

Nvim-R will remain alive as a feature-frozen project for Vim users. If you want to know the reason, please, see [this discussion](https://github.com/jalvesaq/Nvim-R/discussions/797).

Anyway, indentation is not Nvim-R responsibility. So, any issue with indentation should be fixed elsewhere. For Vim, it would be (R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime) which I may stop maintaining because I no longer use Vim, and Neovim is using tree-sitter for syntax highlighting and indentation.

**Comment by dankelley** [comment]
Thanks for this.  I have also switched to neovim.  I'm excited to try the new system you've made.  I can't tell you how much I appreciate all your work, because it lets me work in an editor that is comfortable to me, instead of having to use the RStudio editor or similar.

**Comment by jalvesaq** [comment]
For now, you won't find any big difference. But I hope that more people will contribute to the project since it's no longer in VimScript.
