### ISSUE TITLE
number of separators: 0 () error

### ISSUE THREAD

**Issue by ssh352** [jalvesaq/Nvim-R#584]
I got the error when I load(modeldata) package
https://github.com/tidymodels/modeldata

I've located the error to R/nvimcom/src/apps/nclientserver.c:689

   689     ¦   ¦   ¦   fprintf(stderr, "Number of separators: %d (%s)\n", n, b);

![Uploading Screen Shot 2021-03-31 at 11.00.21 AM.png…]()
<img width="837" alt="Screen Shot 2021-03-31 at 11 04 16 AM" src="https://user-images.githubusercontent.com/41779116/113084594-dd029c80-9210-11eb-895b-489a4dbc6459.png">

**Comment by ssh352** [comment]
Thank you for the quick fix!

**Comment by jmrussell** [comment]
I am still getting this error on the latest nvim-R after deleting and reinstalling nvimcom.

**Comment by jalvesaq** [comment]
The bug originally reported was fixed in nvimcom 0.9-109 and the code fixing it is still there. I could replicate the issue while loading the `modeldata` package. The problem happened because `modeldata` does not export any objects. The current version of nvimcom is 0.9-115 and I can no longer replicate the issue.
