### ISSUE TITLE
Use Neovim native LSP client instead of CompleteR omnicomplete

### ISSUE THREAD

**Issue by inventionate** [jalvesaq/Nvim-R#591]
I am currently running some tests with the native LSP client of Neovim 0.5 (https://neovim.io/doc/user/lsp.html) and the R Languagesrver (https://github.com/REditorSupport/languageserver). In particular, I find the comprehensive completion (no "preloading" of packages) and the code diagnosis as well as the simple code formatting advantageous. Especially since identical commands can be used for different projects with different setups/languages. I don't care about autocompletion. For R scripts, this already works very well by simply overriding the Omnifunc setting globally:

autocmd FileType r setlocal omnifunc=v:lua.vim.lsp.omnifunc

Unfortunately, of course, this means I lose all the Nvim-R advantages in R Markdown. Therefore, my question is whether there will be a possibility in the future to use the LSP omnicompletion just for R chunks (and to keep the chunk-options-completion and Markdown-completion by e.g. Pandoc).

If I can, I am also happy to help with the implementation

**Comment by jalvesaq** [comment]
I'm working right now on a `coc` source to be added to Nvim-R's `autoload` directory to use the current `CompleteR` algorithm. I like the idea of Neovim supporting the language server protocol natively, but I still find `coc-nvim` more full-featured and helpful, at least for the development of C and Python.

I prefer caching data to get faster results, and in Nvim-R the cache is no longer built by the main R process. Now, `nclientserver` runs a separate R instance to build the cache files. The current Nvim-R's omni completion mechanism could easily be adapted as a language server because it transfers a string with a Vim dictionary which is similar to JSON. However, I still need to learn how to write JSON code that would be translated into a Vim completion dictionary. Example of Vim dictionary with just one entry:

```vim
[{'word': 'read.table', 'menu': 'fun [base]'}]
```

Do you know what would be the corresponding JSON code to be transmitted by the language server?

**Comment by inventionate** [comment]
Thanks for the quick reply and the great news. I used CoC for a long time, but then switched to the native LSP client. All in all, all the npm plugins seem a bit bloated to me. The native client can already do a lot, even if it still requires some configuration in Lua. 

Nvim-R as a languageserver would be great, of course, and it would fit perfectly into a good setup. But perhaps it is easier to build on the existing R languageserver? After all, it's not just about completion, the protocol includes many other features. Anyway, as far as I know, all the information about the LSP protocol can be found here:

https://microsoft.github.io/language-server-protocol/

Unfortunately, I have only dealt with it from the user's point of view so far. But if something comes up and I can help, e.g. through tests, I'd be happy to.

**Comment by jalvesaq** [comment]
The languageserver runs in an external R instance. So it doesn't have access to R's memory and, thus, it can't show the summary of columns of data.frames during omni completion or update the `.GlobalEnv` view of the Object Browser. If I run the language server in the main R process, it would slow down R. That's why since the beginning I cached the data for omni completion.

**Comment by inventionate** [comment]
Yes, that's perfect and I love your great package for this well good architecture! Thank you very much. Without your package, R development in Neovim would be much more awkward. I just play around and try different options. Maybe some of them can improve the experience with the package. So I share them here.

The main reason I have been looking at and experimenting with the R language server is that I would like to have omni completion and information about a function or object in a floating window without having to start an R session in Neovim. Quasi directly available when I open an R script. I first tried to adjust R_start_libs, but the omnicompletion only works if I have started R at least once. Am I possibly doing something wrong? If I setup the languageserver (also a seperate process), all information is available without special settings or explicit R startups.

**Comment by jalvesaq** [comment]
> Quasi directly available when I open an R script. I first tried to adjust R_start_libs, but the omnicompletion only works if I have started R at least once.

Now that the cache files are built by an R instance ran by nclientserver, your list of default libraries should be built automatically at Neovim startup. You still have to wait a few seconds the first time, but not start R.

**Comment by inventionate** [comment]
Mhhh, maybe I'm doing something wrong? I changed R_start_libs, e. g. 

`let R_start_libs = 'base,stats,graphics,grDevices,utils,methods,ggplot2'`

and opened a R script. If I trigger omni completion after `ggp` nothing happens. If I start R it works as excpected. It aslo works if I quit the R session. But if I close Neovim and open the script again it's the same situation as before. 

I'm using the latest neovim 0.5 nightly and tested it with both, stable and master branches. I also disabled all non-nvim-r settings and plugins. Maybe you can help me with some debugging tips?

**Comment by jalvesaq** [comment]
Would it be useful to you an option to define what file types should have `CompleteR` as omni function? It could be a list such as:

```
let R_set_omnifunc = ["rmd", "rnoweb", "rhelp"]
```

An empty list would avoid `CompleteR` being set as the omni function in any file type.

**Comment by inventionate** [comment]
Thank you for this idea. But I don't think changes to the code base are necessary. In the meantime, I've been able to create a good setup with the help of [MUComplete](https://github.com/lifepillar/vim-mucomplete):

```vim
" Neovim 0.5 Nightly
set omnifunc = v:lua.vim.lsp.omnifunc

" Nvim-R
autocmd FileType rmd let b:rplugin_non_r_omnifunc = "pandoc#completion#Complete"
autocmd FileType rmd set completefunc=CompleteR

" MUComplete
let g:mucomplete#chains = {}
let g:mucomplete#chains = {
	    \ 'default' : ['omni', 'path'],
	    \ }
let g:mucomplete#chains['rmd'] = {
          \ 'pandocDelimitedCodeBlock_r' : ['omni', 'path'],
          \ 'default'      : ['user', 'path'],
          \ }
```

The ComplereR algorithm is used in R Markdown files for the knitr options and to easily access the Pandoc bib completion. For the R code chunks, the languageserver is used. In this way, all languages are supported in chunks for which a languageserver is available, e. g. Python or Julia, and for all the built-in LSP features (completion, format, rename, async diagnostics, "global" key mappings etc.) are available. I will now use that for a while and see if it's working good.

By the way, there is a small typo in the documentation for the Pandoc setting. The `g:omnifunc=` part must be deleted. 

One thing came up during all the testing that might also be interesting for CompleteR, now that this algorithm is also executed asynchronously. The languageserver analyses all opened scripts and automatically loads all packages loaded via library or require to offer analyses and completions. You can also define standard packages via .Rprofile (as with Nvim-R, here also via `R_start_libs`). As I said, this is possibly a useful extension of the standard behaviour.

For now, I close this issue and again, I really enjoy your great package! Thank you very much!

**Comment by jalvesaq** [comment]
I fixed the typo in the documentation. Thanks!
You found a very interesting way of mixing completion systems in Rmd documents, and your example will certainly be helpful for other users.
I decided to add the new option `R_set_omnifunc` along with `R_auto_omni` because I implemented automatic omni completion and eventually users may want to enable or not either manual or auto omni completion for different file types. Ideally, the `nclientserver` application would follow the language server protocol, so its results could be mixed with the results of other sources. Later, I will more carefully compare the speed of `nclientserver` with that of R's `languageserver` library. If there no significant difference, I will retire at least part of `nclientserver`'s code.
