### ISSUE TITLE
server port undefined if a second r session started

### ISSUE THREAD

**Issue by mdlerch** [jalvesaq/Nvim-R#6]
If I start R (\rf) and eventually close R (\rq) but then start R again (\rf) having never exited my nvim session, then the neovim server port is not passed to R.  I tried to find the bug myself, but did not have any luck.

Here's some relevant output

```
nvim:
\rf (start R the first time)
R:
nvimcom: NVIMR_SVRNM=Neovim_0
nvimcom 0.9.1 loaded
    NVIMR_TMPDIR = /dev/shm/R_tmp_dir
    NVIMR_ID = LaIj8ZY9E43Rx1lBKedjTw
nvimcom port: 10003
nvimcom Received: [1] 1902

nvim:
:echo $NVIMR_SVRNM
Neovim_0

nvim:
:Rhelp lm (help pops up in nvim)
R:
nvimcom_nvimclient(ShowRDoc('lm')): '1902' (1902)

nvim:
\rq (quit R)
\rf (start R again)
R:
nvimcom: NVIMR_SVRNM=Neovim_1902
nvimcom 0.9.1 loaded
    NVIMR_TMPDIR = /dev/shm/R_tmp_dir
    NVIMR_ID = LaIj8ZY9E43Rx1lBKedjTw
nvimcom port: 10003
(((SVRNM is different and nvimcom Received: [1] 1902 does not show up)))

nvim:
:echo $NVIMR_SVRNM
Neovim_1902

nvim:
:Rhelp lm (help does not pop up)
R:
nvimcom_nvimclient(ShowRDoc('lm')): '' (0)
nvimcom_nvimclient() called although Neovim server port is undefined
```

Let me know if there is any more information that would be helpful.

**Comment by jalvesaq** [comment]
Thanks for reporting the bug! I fixed it in the Nvim-R and also deleted the NVIMR_SVRNM environment variable from both Nvim-R and nvimcom. The variable was useful in the Vim-R-plugin because the server was started at Vim startup, but the Nvim-R server is started only after R because we need to know where the nvimserver executable is, and this information is available only after nvimcom is loaded by R.

What happens during R start up after `\rf` is:

  1. Nvim starts R and waits for the file nvimcom_running_ to be created by nvimcom.
  2. nvimcom writes the file nvimcom_running_ in the temporary directory. The file has the following information:
      - nvimcom home directory
      - nvimcom port number
      - R PID
  3. Nvim reads the information from the file.
  4. Nvim checks if the nvimclient and nvimserver executables are in nvimcom home directory.
  5. Nvim starts the client and server jobs
  6. The server job sends a message to Nvim calling the function RSetMyPort() which sends a message to nvimcom informing Nvim's port.

**Comment by mdlerch** [comment]
Thanks for the quick fix!
