### ISSUE TITLE
Unable to install `nvimcom` on MacOs with M1 chip.

### ISSUE THREAD

**Issue by pawelchabros** [jalvesaq/Nvim-R#609]
Hi. Thank you for great package. I use it on linux and wanted to install it on new MacBook. I installed `Nvim-R` plugin and after opening terminal package `nvimcom` is installed and I've got following error:

```
Error: package or namespace load failed for ‘nvimcom’:
 34  .onLoad failed in loadNamespace() for 'nvimcom', details:
 35   call: dyn.load(file, DLLpath = DLLpath, ...)
 36   error: unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/nvimcom/libs/nvimcom.so':
 37   dlopen(/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/nvimcom/libs/nvimcom.so, 10): no suitable image found.  Did find:
 38   /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/nvimcom/libs/nvimcom.so: mach-o, but wrong architecture
```

Does it mean that it's not possible to use this package with arm64 version of R?

**Comment by jalvesaq** [comment]
It's possible because R was built for arm64, so nvimcom can also be built. But, for some reason, your C compiler has built nvimcom with the wrong architecture (either i386 or amd64). I don't know if you have to install a different compiler, change the `PATH` environment variable to make R find the correct compiler, edit the file `Nvim-R/R/nvimcom/src/Makevars`, or do something else. I don't have access to a machine like yours to replicate the issue.

**Comment by pawelchabros** [comment]
`~/.R/Makevars` file from older R version was causing the problem... Sorry for the trouble. Once again thank you for great package!

**Comment by jalvesaq** [comment]
Thanks for the feedback!
