### ISSUE TITLE
Set commentstring for R files

### ISSUE THREAD

**Issue by schoettl** [jalvesaq/Nvim-R#62]
Can this plugin also set the (local) `commentstring`?

I use @tpope's [vim-commentary](https://github.com/tpope/vim-commentary) and I have to set the`commentstring` for R files like this:
```
autocmd FileType r setlocal commentstring=#\ %s
```

Anyway, is it this plugin's responsibility to set filetype-specific variables (like indentation, `makeprg`, `equalprg`, ... and `commentstring`)? If yes, I would love to see `commentstring` supported.

**Comment by jalvesaq** [comment]
`commentstring` is already set by the ftplugin/r.vim that ships with Vim/Neovim. See:
https://github.com/vim/vim/blob/master/runtime/ftplugin/r.vim
https://github.com/neovim/neovim/blob/master/runtime/ftplugin/r.vim

Moreover, I believe that:
   - we don't need `equalprg` because indent/r.vim does the job;
   - we don't need `makeprg` because R is interpreted and not compiled.

Perhaps `makeprg` could be `Rscript\ %` or `R\ CMD\ BATCH\ %`.

**Comment by schoettl** [comment]
I see -- the ftplugins are the right place for this. Thank you. I still wonder why `commentstring` is not automatically set for my `*.R` files in my vim and nvim...

**Comment by jalvesaq** [comment]
On Ubuntu 16.04, it is set automatically in both Vim and Neovim. My vimrc for Vim is:
```vim
set nocompatible
call plug#begin('~/.config/nvim/plugged')
Plug 'jalvesaq/Nvim-R'
call plug#end()
filetype plugin indent on
syntax on
let R_tmux_split = 1
```
Perhaps you have something in your vimrc or in ~/.vim/after/ftplugin/r.vim or somewhere else preventing `commentstring` of being set.

**Comment by schoettl** [comment]
Thank you for you help. Hmm, I can't find the problem. I never change the`commentstring` in my vimrc (except to fix the problem), I have no other plugins related to R, and I have exactly the `r.vim` files (which you mentioned) installed with vim/neovim.

Well, it works with my `autocmd` workaround. Thanks for this great plugin!
