### ISSUE TITLE
Debugging with tmux_split opens a new vim pane for every line in the function

### ISSUE THREAD

**Issue by jamespeapen** [jalvesaq/Nvim-R#629]
When using R in a tmux with `tmux_split.vim` and debugging a function, for every line it opens up the R file in a new vim pane.

https://user-images.githubusercontent.com/39574560/138607083-4d58b9c1-0b91-4094-92d8-79cc0ab5485d.mov

I know you're not officially supporting the `tmux_split.vim` and I'm happy to try to fix it, but any pointers would be helpful.

Thanks!

**Comment by dhersz** [comment]
I still get the same problem, also using R with tmux.

Actually, the problem is not *quite* the same, because in @jamespeapen case every line actually creates *2* new vim buffers. I had exactly the same issue, and after updating the plugin it now creates only *1* new buffer for each new line.

I tried using it the debugger without tmux and didn't find any problem (i.e. the fix worked perfectly for a vim/neovim-only setup). Using `tmux.split` aside, I'm also using the settings (and neovim 0.6.0):

```vim
" ----- Nvim-R -----
let R_nvim_wd = 1                       " wd where vim was originally called
let R_source = '/home/dhersz/.R_tmux_split.vim' " use tmux
let R_assign = 0
let R_app = "radian"
let R_cmd = "R"
let R_hl_term = 0
let R_bracketed_paste = 1
let R_tmux_title = split(getcwd(), '/')[-1] " tmux window with project name
```

Not sure if it's a problem with my setup or if it's something else.

@jamespeapen did the fix work for you?

**Comment by jalvesaq** [comment]
@dhersz, I can't replicate the issue with the Vim script that still ships with Nvim-R (`[...]/Nvim-R/tmux_split.vim`). You are sourcing another one (`/home/dhersz/.R_tmux_split.vim`).

**Comment by dhersz** [comment]
Hmm, this `.R_tmux_split.vim` is actually just a copy of tmux_split with a different name. I tried pointing to `[...]/Nvim-R/tmux_split.vim` but it didn't help either, I still get the same problem.

**Comment by dhersz** [comment]
I found the problem. I'm using Nvim-R to write a package, and am loading the package with `devtools::load_all()`, instead of using `source()`. Once I use `source()` it works fine (note that if I use `load_all()` outside tmux it works fine too).

I'm not sure if you'd call that a feature or a bug, I'll leave that to you :P
