### ISSUE TITLE
Advice fo csv preview integration

### ISSUE THREAD

**Issue by andy941** [jalvesaq/Nvim-R#671]
First of all, I am loving the plugin. I left RStudio and never looked back.
I really like the way that \rv works and let's me preview a properly arranged dataframe in a throw-away new tab. I would like to have something similar to preview csv files but I can't figure it out. I was wondering how you've done it. I am currently using csv.vim, but it doesn't let you arrange the file into a nice table without changing its spacing. How do you create those tabs? I work with bioinformatics datasets and I frequently have to go through results of 2000+ genes, but I don't want/need to change the underlying file.
What I wanted to do was to have a preview tab for CSV files using the csv.vim plugin (CSVArrange), in a "temporary" buffer that doesn't change the underlying file/data, like \rv does. Ideally I would couple that with Nvim-tree or Telescope.

For now I go to the file browser and preview the results of my analyses in excel but that takes a lot of time and I can't easily do it on an ssh connection which is a pain.

I use neovim a lot but I have a lot to learn about its inner workings. I tried reading the help page for tabs but I could find a way to do what I wanted.

Thank you for your time and the amazing plugin,
Andrea

**Comment by jalvesaq** [comment]
Section 6.39 (_View a data.frame or matrix_) has some suggestions. I almost never preview data.frames, but from the few tests that I have done in the past,

```vim
let R_csv_app = 'terminal:vd'
```

should be at least close to what you want. Note that the data.frame isn't changed: R writes a `csv` file that is either loaded by Neovim or opened in another application. For big data.frames, you could try `<LocalLeader>vh` instead of `<LocalLeader>rv`.

**Comment by andy941** [comment]
Thank you very much for the help, I'll try that.
