### ISSUE TITLE
restarting R option?

### ISSUE THREAD

**Issue by berndbischl** [jalvesaq/Nvim-R#68]
Hi,

in the previous vim-r pluging I had a hotkey to start R, but also restart R if it was already running.

I used  let g:vimrplugin_restart = 1            

I saw in your news that you apparently had a restart option for the rewrite of the new plugin, but removed this.

a) Why did you remove this?
b) Is there still a way to  emulate the restarting?

**Comment by jalvesaq** [comment]
Hi,

I removed it because it was too complicated to maintain because Vim and R interact in many alternative ways:

  - Vim in a terminal inside Tmux and R in a split pane.
  - Vim in a terminal and R in another terminal.
  - Gtk Gvim and R in a terminal.
  - Neovim and R running in a Neovim's terminal.
  - MacVim and Rapp
  - Gvim on Windows and Rgui.

The restart was one thing more to test and fix after big changes. And it became more complicated after the plugin has become more and more dependent on vimcom (and now nvimcom) because the connection with vimcom had to be re-established after R was restarted.

Unfortunately, there is no way to emulate it other than quitting R and starting it again.

**Comment by berndbischl** [comment]
ok. thx for your answer (and the plugin).
