### ISSUE TITLE
Recognize `targets` chunk as R code block in Rmd files

### ISSUE THREAD

**Issue by alaindanet** [jalvesaq/Nvim-R#724]
`Nvim-R` does not recognize `targets` chunk as code block containing `R` code in `Rmd` files.

`targets` chunks contains R code that is managed by the `targets` R package to build a [analysis pipeline](https://books.ropensci.org/targets/literate-programming.html#target-markdown).

Is there an option to set `Nvim-R` to behave with `targets` chunk as `r` chunk (i.e. sending code lines to the terminal, etc...) ?

Currently the plugin returns `Not inside an R chunk.` when I try to send lines inside `targets` chunks.

**Comment by jalvesaq** [comment]
I never used `targets`. Indeed, this is the first time that I know about it. What specifically do you need? Sending code from (Neo)Vim from `{targets `  chunks to R? Syntax highlight of `{targets `  chunks? The pattern to recognize chunks of R code in Rmd files is hardcoded in `Nvim-R/ftplugin/rmd_nvimr.vim`, `Nvim-R/R/start_r.vim`, `R-Vim-runtime/syntax/rmd.vim`, and `R-Vim-runtime/indent/rmd.vim`. We could create a variable to replace "r" with whatever the user wanted, in this case, "r\\|targets", but I don't know if this would be enough, and, since I'm not going to use `targets` it would be better if someone else wrote a pull request for this.

**Comment by alaindanet** [comment]
Thank you so much for your answer.
I have spotted some places where the changes could be made.

- In `Nvim-R/ftplugin/rmd_nvimr.vim`:

  - Change `r` to `(r|targets)`? 
 ```vim
function! RmdIsInRCode(vrb)
    let chunkline = search("^[ \t]*```[ ]*{r", "bncW")
```
  - Change `\\(r\\` to `\\(r\\|targets\\`:

```vim
            let i = search("^[ \t]*```[ ]*{\\(r\\|python\\)", "bnW")
```
  - Change `r"` to `(r|targets)"`
```vim
    let chunkline = search("^[ \t]*```[ ]*{r", "bncW") + 1
```
- `Nvim-R/R/start_r.vim`:

  - Change `\\(r\\` to `\\(r\\|targets\\`:
```vim
                    \ ((&filetype == "rmd" || &filetype == "quarto") && line =~ "^[ \t]*```{\\(r\\|python\\)"))
```

-   Change to `(r|targets)`:
```vim
  let begchk = "^[ \t]*```[ ]*{r"
```

- In `R-Vim-runtime/indent/rmd.vim`, change `{r` to `{(r|targets)`:
```vim
 if getline(".") =~ '^[ \t]*```{r .*}$' || getline(".") =~ '^[ \t]*```$'
    return 0
  endif
  if search('^[ \t]*```{r', "bncW") > search('^[ \t]*```$', "bncW")
  ```
  I did not find anything in [R-Vim-runtime](https://github.com/jalvesaq/R-Vim-runtime)/[syntax](https://github.com/jalvesaq/R-Vim-runtime/tree/master/syntax)/rmd.vim
  
If you think that those changes are the ones to implement, I will give a try!

**Comment by jalvesaq** [comment]
Yes, please try it. I suggest that you create a variable, perhaps named `R_chunk_pattern` in your `init.vim`:

```vim
R_chunk_pattern = 'r\|targets'
```

And, then, replace as in the example:

```vim
            let i = search("^[ \t]*```[ ]*{\\(" . R_chunk_pattern . "\\|python\\)", "bnW")
```

I suggest creating a variable because we don't know if another pattern in the future will have to be recognized as an indicator of an R chunk.
