### ISSUE TITLE
The package nvimcom wasn't loaded yet (HPC)

### ISSUE THREAD

**Issue by michaelpreuss** [jalvesaq/Nvim-R#77]
Dear Nvim-R developers,

I've used VIM and vimcom/Nvim-R plugin for several years. Now I've to setup a completely new VIM environment on an HPC where I have to load first modules like R and tmux.
Everything went fine except starting  VIM with plugin for R scripts:
 I get `The package nvimcom wasn't loaded yet.` error message.
Of course, I placed the code from the "nvimcom-not-loaded" topic in my .Rprofile.
I tried it with a waiting time of 20 seconds for loading nvimcom.
However, it still doesn't work :(

The package `nvimcom`  can be loaded if I start R manually.
Can you help me?

**Comment by jalvesaq** [comment]
If the package nvimcom is installed, you can load it normally, like any other package. For example, you can:

   - Put `library("nvimcom")` in your .Rprofile.
   - Set the value of the environment variable `R_DEFAULT_PACKAGES`,
      including `nvimcom` in the list.
   - Load it manually by doing `library("nvimcom")` after R is started.

However, nvimcom is useless if R was not started by Vim/Neovim because Nvim-R sets the values of many environment variables before starting R, and it only starts its own TCP clientserver when starting R. So, R must be started by either Vim or Neovim.

Neovim does not require Tmux to run R, but both R and Vim (or Neovim) must be in the same machine because the TCP communication between them is limited to `localhost` and the communication through cached and temporary files requires that both R and Vim/Neovim have access to the same directories. Please, see the explanation on the communication between Vim/Neovim and R at the end of https://github.com/jalvesaq/Nvim-R/blob/master/README.md

**Comment by michaelpreuss** [comment]
Finally it works now! It seems that I had to set the temporary files directories to an other place.

**Comment by jalvesaq** [comment]
Could you, please, explain what places? The information could be useful for other people.

**Comment by michaelpreuss** [comment]
I set temporary paths to my home directory `~/tmp`, where I have full permissions.
   'let R_tmpdir =~/tmp'
   'let R_compldir = ~/tmp'
Maybe the second one isn't necessary.
