### ISSUE TITLE
The plugin no longer works on Windows

### ISSUE THREAD

**Issue by jalvesaq** [jalvesaq/Nvim-R#775]
The TCP connection is broken on Windows. This means that the plugin only works on a Unix platform such as Linux or Mac OS X.
A pull request fixing the TCP connection is welcome. Previously, the connection was through UDP.

People on Windows have to choose a version before https://github.com/jalvesaq/Nvim-R/commit/8a9293b261dab3f2d543ec060716bf8bcfb05066

I'm sorry, but I can no longer maintain the Windows version.

**Comment by akthe-at** [comment]
I just wanted to thank you @jalvesaq for working to fix this and get nvim-r working on Windows. When I first saw this I was pretty bummed because I had just found nvim-r and was very excited to try it (new to neovim/vim) and I did not want to keep using Rstudio or VSC. I use R a lot at work on pretty securely locked down computers with no option for mac/linux/WSL2....As of your commits the other day, I can now use nvim-r and it is pretty dang slick and useful. Thank YOU.
