### ISSUE TITLE
Highlighting Issue with Anonymous Functions (\(x))

### ISSUE THREAD

**Issue by wklm** [jalvesaq/Nvim-R#819]
First off, thanks for the awesome plugin!
I just wanted to flag a small issue I came across. It seems that anonymous functions (\(x)), which were introduced in R 4.1.0, aren't being highlighted correctly. 

<img width="1103" alt="Screenshot 2024-12-02 at 14 02 13" src="https://github.com/user-attachments/assets/13601bb6-8a9b-436d-91c4-d0343a39487a">

### Steps to Reproduce:
Open an R script in Vim with Nvim-R.
Add some anonymous functions, like \\(x) x + 1.
Notice that the highlighting doesn’t work for \\(x).

### Environment:
Vim Version: 9.1
Nvim-R Version: Latest (commit b7cdc9bcd6879465023e20b4a3ae16968edda776)
R Version: 4.1.0+

### Expected Behavior: 
It’d be great if \(x) was highlighted like other function definitions for better readability.

**Comment by jalvesaq** [comment]
I'm sorry, but I'm no longer the maintainer of `~/syntax/r.vim`. Please, see: https://github.com/jalvesaq/R-Vim-runtime

**Comment by jranke** [comment]
Hi @wklm, I would like to add that I had the same issue, but it was because I hadn't updated `R-Vim-runtime` which obtained this feature on February 24 2023 [1]. It was merged into `vim/vim`on github on February 27 [2]. By the way, it would be more precise to say "Shorthand form of function definitions" or something similar, as conventional functions defined with the `function` keyword can also be anonymous. I will now deactivate `R-Vim-runtime`, as it seems everything has been merged upstream. Thanks a lot @jalvesaq for maintaining and improving `syntax/r.vim` for so long! These syntax files are daunting, and it always takes a long time (at least for me) to figure out what to do if one wants to change something. See you over at `R.nvim` [3]! 

[1] https://github.com/jalvesaq/R-Vim-runtime/pull/54
[2] https://github.com/vim/vim/blame/bdb5f85a5189534653f36e92b1bc780ca8d25218/runtime/syntax/r.vim#L314
[3] https://github.com/R-nvim/R.nvim!
