### ISSUE TITLE
File is saved on source (\aa)

### ISSUE THREAD

**Issue by enricoferrero** [jalvesaq/Nvim-R#83]
I've noticed than when sourcing the entire file (`\aa`) the file is saved, which is undesirable.
I understand vim needs to save the files somewhere to source it but it should not overwrite the original file. Maybe a temporary file (similar to what happens with `\pp` or `\ss`) is the solution here.

Is there an option that I can edit to turn this behavior off?

Thanks

**Comment by jalvesaq** [comment]
I agree with you: the behavior of both `\aa` and `\ae` is inconsistent with `\ss` and `\pp`. Only `\ao` should save the file.

**Comment by claytontstanley** [comment]
Here's a use case for sourcing the file in place (and saving): Code in the file that relies on a relative path starting from the location of the file still works.

For example, you set the PATH to the .R file at the top of the file, and use PATH to load data files stored in the repository at a location relative to the file location (e.g., "./data"). Since the code was sent to a tmp file before being executed, any data files that are defined in reference to the PATH to the actual .R file (not the temp file) will not be accurate, since on execution, PATH is set to the created tmp file.

That is, I have this code at the top of all my .R files:

PATH = getPathToThisFile()

Where getPathToThisFile is defined in my .Rprofile:

getPathToThisFile = function() {
        frameFiles = lapply(sys.frames(), function(x) x$ofile)
        frameFiles = Filter(Negate(is.null), frameFiles)
        dirname(frameFiles[[length(frameFiles)]])
}

**Comment by jalvesaq** [comment]
@claytontstanley The problem should be fixed now: https://github.com/jalvesaq/Nvim-R/commit/930c70eb5d258ba8fbbd3b037a3b05190f29bf4d

**Comment by claytontstanley** [comment]
Works great. Nice solution that solves both perspectives in this thread.
