### ISSUE TITLE
LD_LIBRARY_PATH obliterated

### ISSUE THREAD

**Issue by JohnReid** [jalvesaq/Nvim-R#99]
I start neovim from a shell with my `LD_LIBRARY_PATH` set correctly and then start R from with neovim. However in the new R session I get a different setting with `Sys.getenv('LD_LIBRARY_PATH')`. Is there any reason neovim or Nvim-R would change this environment variable?

**Comment by jalvesaq** [comment]
Nvim-R does not change the value of `LD_LIBRARY_PATH`. If you want to check:
```
cd /path/to/Nvim-R
grep -R LD_LIBRARY_PATH
```

**Comment by JohnReid** [comment]
So I'm confused. If I start R from a terminal then the existing `LD_LIBRARY_PATH` is respected. If I start R from inside neovim then `LD_LIBRARY_PATH` is different. I have no idea why.

**Comment by JohnReid** [comment]
I think it might be because nvim-r starts a new tmux pane and this new tmux pane starts a new shell.

**Comment by jalvesaq** [comment]
And what happens if you run R in a Neovim buffer (`let R_in_buffer = 1`)?

**Comment by JohnReid** [comment]
I get `E117: Unknown function: StartR_Neovim`

**Comment by jalvesaq** [comment]
I put `export LD_LIBRARY_PATH=/tmp` in my .bashrc and I can't reproduce the bug. R does change the value of `LD_LIBRARY_PATH`, but it does this regardless of being started by Neovim or not.

The `Unknown function` error means that you have a broken Nvim-R installation. Perhaps you have deleted some files or mixed different versions of Vim-R-plugin and Nvim-R. This would happen if you have used different methods to install different versions.

**Comment by JohnReid** [comment]
I was worried my installation was a bit flaky. It is hard to keep track of the changing versions and names... I shall keep investigating

**Comment by JohnReid** [comment]
I can't work out what is broken at all. I don't have Vim-R-plugin and I have a clean install of Nvim-R. Can you suggest how I can find out what is broken? I use plugged for my plugins.

**Comment by jalvesaq** [comment]
It seems that the file Nvim-R/R/nvimbuffer.vim is missing.

**Comment by JohnReid** [comment]
That file is there: `~/.config/nvim/plugged/Nvim-R/R/nvimbuffer.vim` and has the `StartR_Neovim()` function in it. I guess neovim must be looking elsewhere.

**Comment by jalvesaq** [comment]
This command in Neovim might be helpful: `:scriptnames`

**Comment by jalvesaq** [comment]
Any news on this issue?

**Comment by JohnReid** [comment]
No real news. I tried to get it to work but had no luck. At the moment I'm not working with the package that needed the environment variable set correctly.

**Comment by claytontstanley** [comment]
I had the same issue and it was due to a custom setup where the default shell (not set my me; by the admins) was different than the my preferred shell (bash). So my workflow was to launch shell, then hit $bash, then tmux, then $bash, then:

R -> Sys.getenv('LD_LIBRARY_PATH') -> correct
vim -> \rf -> Sys.getenv('LD_LIBRARY_PATH') -> incorrect

This was due to tmux launching the default (not bash) shell for every new pane, which indirectly happens after \rf with Nvim-r.

The fix for me was to express directly in ~/.tmux.conf which shell I wanted when creating a new pane, so I added this line:

set-option -g default-shell /bin/bash

And then everything worked with the workflow: launch shell -> $bash -> $tmux ->:
R -> Sys.getenv('LD_LIBRARY_PATH') -> correct
vim -> \rf -> Sys.getenv('LD_LIBRARY_PATH') -> correct

**Comment by jalvesaq** [comment]
Please, see https://github.com/jalvesaq/Nvim-R/issues/171#issuecomment-287509421 and https://github.com/jalvesaq/Nvim-R/issues/154#issuecomment-289007687
One of them might be useful.

**Comment by JohnReid** [comment]
Thanks, this appears to be working for me now.
